CONNECT TO SIAK USER SIAK;
ALTER TABLE SIAK.MMAHASISWA ALTER COLUMN CTUJUAN SET DATA TYPE VARCHAR ( 300 ) ;
CONNECT RESET;

CONNECT TO SIAK USER SIAK;
ALTER TABLE SIAK.MHISTKURSUSMHS ALTER COLUMN CLAMA SET DATA TYPE VARCHAR ( 100 ) ;
CONNECT RESET;