CONNECT TO SIAK USER SIAK;
ALTER TABLE SIAK.MMAHASISWA ALTER COLUMN CTUJUAN SET DATA TYPE VARCHAR ( 1000 ) ;
CONNECT RESET;

CONNECT TO SIAK USER SIAK;
ALTER TABLE SIAK.MHISTKURSUSMHS ALTER COLUMN CLAMA SET DATA TYPE VARCHAR ( 100 ) ;
CONNECT RESET;

CONNECT TO SIAK USER SIAK;
ALTER TABLE SIAK.MKGTMHS ALTER COLUMN CNMSIMPOSIUM SET DATA TYPE VARCHAR ( 200 ) ;
CONNECT RESET;

CONNECT TO SIAK USER SIAK;
ALTER TABLE SIAK.MHISTKURSUSMHS ALTER COLUMN CNMKURSUS SET DATA TYPE VARCHAR ( 100 ) ;
CONNECT RESET;

CONNECT TO SIAK USER SIAK;
ALTER TABLE SIAK.MPRESTASIMHS ALTER COLUMN CNMPRESTASI SET DATA TYPE VARCHAR ( 100 ) ;
CONNECT RESET;