CONNECT TO SIAK USER SIAK;
INSERT INTO MSTATUSMHS(ID,CKDSTATMHS,CNMSTATMHS,CKETERANGAN)
VALUES('-1','1','AKTIF','AKTIF'); 
COMMIT ;

INSERT INTO MSTATUSMHS(ID,CKDSTATMHS,CNMSTATMHS,CKETERANGAN)
VALUES('-2','2','CUTI','CUTI'); 
COMMIT ;

INSERT INTO MJENJANG(ID,CKDJEN,CNMJEN,CSINGKAT)
VALUES('1','S1','Sarjana','S1'); 
COMMIT ;

INSERT INTO MJENJANG(ID,CKDJEN,CNMJEN,CSINGKAT)
VALUES('2','S2','Pasca Sarjana','S2'); 
COMMIT ;

CONNECT RESET;

