--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "MALUMNI" DROP CONSTRAINT "FK_KEL";

ALTER TABLE "MALUMNI" DROP CONSTRAINT "FK_SEKOLAH";

ALTER TABLE "MALUMNI" DROP CONSTRAINT "FK_PROP";

ALTER TABLE "MALUMNI" DROP CONSTRAINT "FK_KAB";

ALTER TABLE "MALUMNI" DROP CONSTRAINT "FK_MAHASISWA";

ALTER TABLE "MALUMNI" DROP CONSTRAINT "FK_PRODI";

ALTER TABLE "MALUMNI" DROP CONSTRAINT "FK_KEC";

ALTER TABLE "MALUMNI" DROP CONSTRAINT "PK_MALUMNI";

DROP INDEX "PK_MALUMNI";

DROP TABLE "MALUMNI";

CREATE TABLE "MALUMNI" (
		"ID" INTEGER NOT NULL,
		"SEKOLAH_ID" INTEGER,
		"PRODI_ID" INTEGER,
		"CTERM" CHAR(4),
		"MAHASISWA_ID" INTEGER NOT NULL,
		"CALAMAT" VARCHAR(100),
		"CKDPOS" CHAR(5),
		"PROP_ID" INTEGER,
		"KAB_ID" INTEGER,
		"KEC_ID" INTEGER,
		"KEL_ID" INTEGER,
		"CNOTELP" CHAR(15),
		"CNOHP" CHAR(15),
		"CSTATNKH" CHAR(1) DEFAULT 'N',
		"CKDAGAMA" CHAR(1) DEFAULT '0',
		"CSUDAHKERJA" CHAR(1) DEFAULT 'N',
		"CCREATEDBY" VARCHAR(35),
		"DCREATEDDATE" DATE,
		"CUPDATEDBY" VARCHAR(35),
		"DUPDATEDDATE" DATE
	);

CREATE UNIQUE INDEX "PK_MALUMNI" ON "MALUMNI" ("ID" ASC);

ALTER TABLE "MALUMNI" ADD CONSTRAINT "PK_MALUMNI" PRIMARY KEY ("ID");

ALTER TABLE "MALUMNI" ADD CONSTRAINT "FK_KEL" FOREIGN KEY ("KEL_ID")
	REFERENCES "MKEL" ("ID");

ALTER TABLE "MALUMNI" ADD CONSTRAINT "FK_SEKOLAH" FOREIGN KEY ("SEKOLAH_ID")
	REFERENCES "MSEKOLAH" ("ID");

ALTER TABLE "MALUMNI" ADD CONSTRAINT "FK_PROP" FOREIGN KEY ("PROP_ID")
	REFERENCES "MPROV" ("ID");

ALTER TABLE "MALUMNI" ADD CONSTRAINT "FK_KAB" FOREIGN KEY ("KAB_ID")
	REFERENCES "MKAB" ("ID");

ALTER TABLE "MALUMNI" ADD CONSTRAINT "FK_MAHASISWA" FOREIGN KEY ("MAHASISWA_ID")
	REFERENCES "MMAHASISWA" ("ID");

ALTER TABLE "MALUMNI" ADD CONSTRAINT "FK_PRODI" FOREIGN KEY ("PRODI_ID")
	REFERENCES "MPRODI" ("ID");

ALTER TABLE "MALUMNI" ADD CONSTRAINT "FK_KEC" FOREIGN KEY ("KEC_ID")
	REFERENCES "MKEC" ("ID");

