package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Malumni generated by hbm2java
 */
public class Malumni  implements java.io.Serializable {


     private int id;
     private Mprov mprov;
     private Msekolah msekolah;
     private Mprodi mprodi;
     private Mkab mkab;
     private Mmahasiswa mmahasiswa;
     private Mkel mkel;
     private Mkec mkec;
     private String cterm;
     private String calamat;
     private String ckdpos;
     private String cnotelp;
     private String cnohp;
     private char cstatnkh;
     private char ckdagama;
     private char csudahkerja;
     private String ccreatedby;
     private Date dcreateddate;
     private String cupdatedby;
     private Date dupdateddate;
     private Set<Tfeedbackinstansi> tfeedbackinstansis = new HashSet<Tfeedbackinstansi>(0);

    public Malumni() {
    }

	
    public Malumni(int id, Mprov mprov, Msekolah msekolah, Mprodi mprodi, Mkab mkab, Mmahasiswa mmahasiswa, Mkel mkel, Mkec mkec, String cterm, String calamat, String ckdpos, char cstatnkh) {
        this.id = id;
        this.mprov = mprov;
        this.msekolah = msekolah;
        this.mprodi = mprodi;
        this.mkab = mkab;
        this.mmahasiswa = mmahasiswa;
        this.mkel = mkel;
        this.mkec = mkec;
        this.cterm = cterm;
        this.calamat = calamat;
        this.ckdpos = ckdpos;
        this.cstatnkh = cstatnkh;
    }
    public Malumni(int id, Mprov mprov, Msekolah msekolah, Mprodi mprodi, Mkab mkab, Mmahasiswa mmahasiswa, Mkel mkel, Mkec mkec, String cterm, String calamat, String ckdpos, String cnotelp, String cnohp, char cstatnkh, char ckdagama, char csudahkerja, String ccreatedby, Date dcreateddate, String cupdatedby, Date dupdateddate, Set<Tfeedbackinstansi> tfeedbackinstansis) {
       this.id = id;
       this.mprov = mprov;
       this.msekolah = msekolah;
       this.mprodi = mprodi;
       this.mkab = mkab;
       this.mmahasiswa = mmahasiswa;
       this.mkel = mkel;
       this.mkec = mkec;
       this.cterm = cterm;
       this.calamat = calamat;
       this.ckdpos = ckdpos;
       this.cnotelp = cnotelp;
       this.cnohp = cnohp;
       this.cstatnkh = cstatnkh;
       this.ckdagama = ckdagama;
       this.csudahkerja = csudahkerja;
       this.ccreatedby = ccreatedby;
       this.dcreateddate = dcreateddate;
       this.cupdatedby = cupdatedby;
       this.dupdateddate = dupdateddate;
       this.tfeedbackinstansis = tfeedbackinstansis;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mprov getMprov() {
        return this.mprov;
    }
    
    public void setMprov(Mprov mprov) {
        this.mprov = mprov;
    }
    public Msekolah getMsekolah() {
        return this.msekolah;
    }
    
    public void setMsekolah(Msekolah msekolah) {
        this.msekolah = msekolah;
    }
    public Mprodi getMprodi() {
        return this.mprodi;
    }
    
    public void setMprodi(Mprodi mprodi) {
        this.mprodi = mprodi;
    }
    public Mkab getMkab() {
        return this.mkab;
    }
    
    public void setMkab(Mkab mkab) {
        this.mkab = mkab;
    }
    public Mmahasiswa getMmahasiswa() {
        return this.mmahasiswa;
    }
    
    public void setMmahasiswa(Mmahasiswa mmahasiswa) {
        this.mmahasiswa = mmahasiswa;
    }
    public Mkel getMkel() {
        return this.mkel;
    }
    
    public void setMkel(Mkel mkel) {
        this.mkel = mkel;
    }
    public Mkec getMkec() {
        return this.mkec;
    }
    
    public void setMkec(Mkec mkec) {
        this.mkec = mkec;
    }
    public String getCterm() {
        return this.cterm;
    }
    
    public void setCterm(String cterm) {
        this.cterm = cterm;
    }
    public String getCalamat() {
        return this.calamat;
    }
    
    public void setCalamat(String calamat) {
        this.calamat = calamat;
    }
    public String getCkdpos() {
        return this.ckdpos;
    }
    
    public void setCkdpos(String ckdpos) {
        this.ckdpos = ckdpos;
    }
    public String getCnotelp() {
        return this.cnotelp;
    }
    
    public void setCnotelp(String cnotelp) {
        this.cnotelp = cnotelp;
    }
    public String getCnohp() {
        return this.cnohp;
    }
    
    public void setCnohp(String cnohp) {
        this.cnohp = cnohp;
    }
    public char getCstatnkh() {
        return this.cstatnkh;
    }
    
    public void setCstatnkh(char cstatnkh) {
        this.cstatnkh = cstatnkh;
    }
    public char getCkdagama() {
        return this.ckdagama;
    }
    
    public void setCkdagama(char ckdagama) {
        this.ckdagama = ckdagama;
    }
    public char getCsudahkerja() {
        return this.csudahkerja;
    }
    
    public void setCsudahkerja(char csudahkerja) {
        this.csudahkerja = csudahkerja;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public Set<Tfeedbackinstansi> getTfeedbackinstansis() {
        return this.tfeedbackinstansis;
    }
    
    public void setTfeedbackinstansis(Set<Tfeedbackinstansi> tfeedbackinstansis) {
        this.tfeedbackinstansis = tfeedbackinstansis;
    }




}


