package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.Set;

/**
 * Mbidangusaha generated by hbm2java
 */
public class Mbidangusaha  implements java.io.Serializable {


     private int id;
     private String cbidushins;
     private String cnmbidusaha;
     private String ccreatedby;
     private Date dcreateddate;
     private String cupdatedby;
     private Date cupdateddate;


    public Mbidangusaha() {
    }

	
    public Mbidangusaha(int id, String cbidushins, String cnmbidusaha) {
        this.id = id;
        this.cbidushins = cbidushins;
        this.cnmbidusaha = cnmbidusaha;
    }
    public Mbidangusaha(int id, String cbidushins, String cnmbidusaha, String ccreatedby, Date dcreateddate, String cupdatedby, Date cupdateddate, Set<Thistkerja> thistkerjas) {
       this.id = id;
       this.cbidushins = cbidushins;
       this.cnmbidusaha = cnmbidusaha;
       this.ccreatedby = ccreatedby;
       this.dcreateddate = dcreateddate;
       this.cupdatedby = cupdatedby;
       this.cupdateddate = cupdateddate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCbidushins() {
        return this.cbidushins;
    }
    
    public void setCbidushins(String cbidushins) {
        this.cbidushins = cbidushins;
    }
    public String getCnmbidusaha() {
        return this.cnmbidusaha;
    }
    
    public void setCnmbidusaha(String cnmbidusaha) {
        this.cnmbidusaha = cnmbidusaha;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }
    public Date getCupdateddate() {
        return this.cupdateddate;
    }
    
    public void setCupdateddate(Date cupdateddate) {
        this.cupdateddate = cupdateddate;
    }

}


