package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Mdetilkurikulum generated by hbm2java
 */
public class Mdetilkurikulum  implements java.io.Serializable {


     private int id;
     private Mprodi mprodi;
     private Mtbmtkl mtbmtkl;
     private String ckodekur;
     private String ccohort;
     private String cjenis;
     private String cstatus;
     private String cmun;
     private String clintasprodi;
     private String ctermsmt;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;

    public Mdetilkurikulum() {
    }

	
    public Mdetilkurikulum(int id, Mprodi mprodi, String ckodekur) {
        this.id = id;
        this.mprodi = mprodi;
        this.ckodekur = ckodekur;
    }
    public Mdetilkurikulum(int id, Mprodi mprodi, Mtbmtkl mtbmtkl, String ckodekur, String ccohort, String cjenis, String cstatus, String cmun, String clintasprodi, String ctermsmt, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby) {
       this.id = id;
       this.mprodi = mprodi;
       this.mtbmtkl = mtbmtkl;
       this.ckodekur = ckodekur;
       this.ccohort = ccohort;
       this.cjenis = cjenis;
       this.cstatus = cstatus;
       this.cmun = cmun;
       this.clintasprodi = clintasprodi;
       this.ctermsmt = ctermsmt;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mprodi getMprodi() {
        return this.mprodi;
    }
    
    public void setMprodi(Mprodi mprodi) {
        this.mprodi = mprodi;
    }
    public Mtbmtkl getMtbmtkl() {
        return this.mtbmtkl;
    }
    
    public void setMtbmtkl(Mtbmtkl mtbmtkl) {
        this.mtbmtkl = mtbmtkl;
    }
    public String getCkodekur() {
        return this.ckodekur;
    }
    
    public void setCkodekur(String ckodekur) {
        this.ckodekur = ckodekur;
    }
    public String getCcohort() {
        return this.ccohort;
    }
    
    public void setCcohort(String ccohort) {
        this.ccohort = ccohort;
    }
    public String getCjenis() {
        return this.cjenis;
    }
    
    public void setCjenis(String cjenis) {
        this.cjenis = cjenis;
    }
    public String getCstatus() {
        return this.cstatus;
    }
    
    public void setCstatus(String cstatus) {
        this.cstatus = cstatus;
    }
    public String getCmun() {
        return this.cmun;
    }
    
    public void setCmun(String cmun) {
        this.cmun = cmun;
    }
    public String getClintasprodi() {
        return this.clintasprodi;
    }
    
    public void setClintasprodi(String clintasprodi) {
        this.clintasprodi = clintasprodi;
    }
    public String getCtermsmt() {
        return this.ctermsmt;
    }
    
    public void setCtermsmt(String ctermsmt) {
        this.ctermsmt = ctermsmt;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }




}


