package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mgrade generated by hbm2java
 */
public class Mgrade  implements java.io.Serializable {


     private int id;
     private Mprodi mprodi;
     private Mjenjang mjenjang;
     private String ckdgrade;
     private String cgrade;
     private Double nbobot;
     private Double nnilawal;
     private Double nnilakhir;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdatedate;
     private String dupdatedby;
     private Set<Tirspasca> tirspascas = new HashSet<Tirspasca>(0);
     private Set<Tlognilai> tlognilais = new HashSet<Tlognilai>(0);

    public Mgrade() {
    }

	
    public Mgrade(int id) {
        this.id = id;
    }

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mprodi getMprodi() {
        return this.mprodi;
    }
    
    public void setMprodi(Mprodi mprodi) {
        this.mprodi = mprodi;
    }
    public Mjenjang getMjenjang() {
        return this.mjenjang;
    }
    
    public void setMjenjang(Mjenjang mjenjang) {
        this.mjenjang = mjenjang;
    }
    public String getCkdgrade() {
        return this.ckdgrade;
    }
    
    public void setCkdgrade(String ckdgrade) {
        this.ckdgrade = ckdgrade;
    }
    public String getCgrade() {
        return this.cgrade;
    }
    
    public void setCgrade(String cgrade) {
        this.cgrade = cgrade;
    }
    public Double getNbobot() {
        return this.nbobot;
    }
    
    public void setNbobot(Double nbobot) {
        this.nbobot = nbobot;
    }
    public Double getNnilawal() {
        return this.nnilawal;
    }
    
    public void setNnilawal(Double nnilawal) {
        this.nnilawal = nnilawal;
    }
    public Double getNnilakhir() {
        return this.nnilakhir;
    }
    
    public void setNnilakhir(Double nnilakhir) {
        this.nnilakhir = nnilakhir;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdatedate() {
        return this.dupdatedate;
    }
    
    public void setDupdatedate(Date dupdatedate) {
        this.dupdatedate = dupdatedate;
    }
    public String getDupdatedby() {
        return this.dupdatedby;
    }
    
    public void setDupdatedby(String dupdatedby) {
        this.dupdatedby = dupdatedby;
    }
    public Set<Tirspasca> getTirspascas() {
        return this.tirspascas;
    }
    
    public void setTirspascas(Set<Tirspasca> tirspascas) {
        this.tirspascas = tirspascas;
    }
    public Set<Tlognilai> getTlognilais() {
        return this.tlognilais;
    }
    
    public void setTlognilais(Set<Tlognilai> tlognilais) {
        this.tlognilais = tlognilais;
    }




}


