package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Mhistkursusmhs generated by hbm2java
 */
public class Mhistkursusmhs  implements java.io.Serializable {


     private int id;
     private int mahasiswaId;
     private String cno;
     private String cnmkursus;
     private String clama;
     private String cthnselesai;
     private String ctempat;
     private String cket;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;

    public Mhistkursusmhs() {
    }

	
    public Mhistkursusmhs(int id, int mahasiswaId, String cno) {
        this.id = id;
        this.mahasiswaId = mahasiswaId;
        this.cno = cno;
    }
    public Mhistkursusmhs(int id, int mahasiswaId, String cno, String cnmkursus, String clama, String cthnselesai, String ctempat, String cket, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby) {
       this.id = id;
       this.mahasiswaId = mahasiswaId;
       this.cno = cno;
       this.cnmkursus = cnmkursus;
       this.clama = clama;
       this.cthnselesai = cthnselesai;
       this.ctempat = ctempat;
       this.cket = cket;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    public int getMahasiswaId() {
        return mahasiswaId;
    }

    public void setMahasiswaId(int mahasiswaId) {
        this.mahasiswaId = mahasiswaId;
    }

    public String getCno() {
        return this.cno;
    }
    
    public void setCno(String cno) {
        this.cno = cno;
    }
    public String getCnmkursus() {
        return this.cnmkursus;
    }
    
    public void setCnmkursus(String cnmkursus) {
        this.cnmkursus = cnmkursus;
    }
    public String getClama() {
        return this.clama;
    }
    
    public void setClama(String clama) {
        this.clama = clama;
    }
    public String getCthnselesai() {
        return this.cthnselesai;
    }
    
    public void setCthnselesai(String cthnselesai) {
        this.cthnselesai = cthnselesai;
    }
    public String getCtempat() {
        return this.ctempat;
    }
    
    public void setCtempat(String ctempat) {
        this.ctempat = ctempat;
    }
    public String getCket() {
        return this.cket;
    }
    
    public void setCket(String cket) {
        this.cket = cket;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }




}


