package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Mkaryamhs generated by hbm2java
 */
public class Mkaryamhs  implements java.io.Serializable {


     private int id;
     private int mahasiswaId;
     private String cno;
     private String cnmkyrilm;
     private String cmediaterbit;
     private String cthnterbit;
     private String cket;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;

    public Mkaryamhs() {
    }

	
    public Mkaryamhs(int id, int mahasiswaId, String cno) {
        this.id = id;
        this.mahasiswaId = mahasiswaId;
        this.cno = cno;
    }
    public Mkaryamhs(int id, int mahasiswaId, String cno, String cnmkyrilm, String cmediaterbit, String cthnterbit, String cket, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby) {
       this.id = id;
       this.mahasiswaId = mahasiswaId;
       this.cno = cno;
       this.cnmkyrilm = cnmkyrilm;
       this.cmediaterbit = cmediaterbit;
       this.cthnterbit = cthnterbit;
       this.cket = cket;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getMahasiswaId() {
        return this.mahasiswaId;
    }
    
    public void setMahasiswaId(int mahasiswaId) {
        this.mahasiswaId = mahasiswaId;
    }
    public String getCno() {
        return this.cno;
    }
    
    public void setCno(String cno) {
        this.cno = cno;
    }
    public String getCnmkyrilm() {
        return this.cnmkyrilm;
    }
    
    public void setCnmkyrilm(String cnmkyrilm) {
        this.cnmkyrilm = cnmkyrilm;
    }
    public String getCmediaterbit() {
        return this.cmediaterbit;
    }
    
    public void setCmediaterbit(String cmediaterbit) {
        this.cmediaterbit = cmediaterbit;
    }
    public String getCthnterbit() {
        return this.cthnterbit;
    }
    
    public void setCthnterbit(String cthnterbit) {
        this.cthnterbit = cthnterbit;
    }
    public String getCket() {
        return this.cket;
    }
    
    public void setCket(String cket) {
        this.cket = cket;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }




}


