package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Mkurmhs generated by hbm2java
 */
public class Mkurmhs  implements java.io.Serializable {

    //public static String ID = "";
    //public static String PRODI = "";
    //public static String COHORT = "";
    //public static String KURIKULUM = "";
     private int id;
     private Mprodi mprodi;
     private Mmahasiswa mmahasiswa;
     private Mkurikulum mkurikulum;
     private String cthajar;
     private String cterm;
     private String ccohort;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;

    public Mkurmhs() {
    }

	
    public Mkurmhs(int id, Mprodi mprodi, Mmahasiswa mmahasiswa, Mkurikulum mkurikulum, String ccohort) {
        this.id = id;
        this.mprodi = mprodi;
        this.mmahasiswa = mmahasiswa;
        this.mkurikulum = mkurikulum;
        this.ccohort = ccohort;
    }
    public Mkurmhs(int id, Mprodi mprodi, Mmahasiswa mmahasiswa, Mkurikulum mkurikulum, String cthajar, String cterm, String ccohort, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby) {
       this.id = id;
       this.mprodi = mprodi;
       this.mmahasiswa = mmahasiswa;
       this.mkurikulum = mkurikulum;
       this.cthajar = cthajar;
       this.cterm = cterm;
       this.ccohort = ccohort;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mprodi getMprodi() {
        return this.mprodi;
    }
    
    public void setMprodi(Mprodi mprodi) {
        this.mprodi = mprodi;
    }
    public Mmahasiswa getMmahasiswa() {
        return this.mmahasiswa;
    }
    
    public void setMmahasiswa(Mmahasiswa mmahasiswa) {
        this.mmahasiswa = mmahasiswa;
    }
    public Mkurikulum getMkurikulum() {
        return this.mkurikulum;
    }
    
    public void setMkurikulum(Mkurikulum mkurikulum) {
        this.mkurikulum = mkurikulum;
    }
    public String getCthajar() {
        return this.cthajar;
    }
    
    public void setCthajar(String cthajar) {
        this.cthajar = cthajar;
    }
    public String getCterm() {
        return this.cterm;
    }
    
    public void setCterm(String cterm) {
        this.cterm = cterm;
    }
    public String getCcohort() {
        return this.ccohort;
    }
    
    public void setCcohort(String ccohort) {
        this.ccohort = ccohort;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }




}


