package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Mmhspascakhs generated by hbm2java
 */
public class Mmhspascakhs  implements java.io.Serializable {


     private int id;
     private Mpangkatgolongan mpangkatgolongan;
     private Mmahasiswa mmahasiswa;
     private Mjabatan mjabatan;
     private String cnip;
     private String ckesatuan;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;

    public Mmhspascakhs() {
    }

	
    public Mmhspascakhs(int id, Mmahasiswa mmahasiswa) {
        this.id = id;
        this.mmahasiswa = mmahasiswa;
    }
    public Mmhspascakhs(int id, Mpangkatgolongan mpangkatgolongan, Mmahasiswa mmahasiswa, Mjabatan mjabatan, String cnip, String ckesatuan, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby) {
       this.id = id;
       this.mpangkatgolongan = mpangkatgolongan;
       this.mmahasiswa = mmahasiswa;
       this.mjabatan = mjabatan;
       this.cnip = cnip;
       this.ckesatuan = ckesatuan;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mpangkatgolongan getMpangkatgolongan() {
        return this.mpangkatgolongan;
    }
    
    public void setMpangkatgolongan(Mpangkatgolongan mpangkatgolongan) {
        this.mpangkatgolongan = mpangkatgolongan;
    }
    public Mmahasiswa getMmahasiswa() {
        return this.mmahasiswa;
    }
    
    public void setMmahasiswa(Mmahasiswa mmahasiswa) {
        this.mmahasiswa = mmahasiswa;
    }
    public Mjabatan getMjabatan() {
        return this.mjabatan;
    }
    
    public void setMjabatan(Mjabatan mjabatan) {
        this.mjabatan = mjabatan;
    }
    public String getCnip() {
        return this.cnip;
    }
    
    public void setCnip(String cnip) {
        this.cnip = cnip;
    }
    public String getCkesatuan() {
        return this.ckesatuan;
    }
    
    public void setCkesatuan(String ckesatuan) {
        this.ckesatuan = ckesatuan;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }




}


