package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Mpbahasamhs generated by hbm2java
 */
public class Mpbahasamhs  implements java.io.Serializable {


     private int id;
     private Mmahasiswa mmahasiswa;
     private String cno;
     private String cnmbahasa;
     private String cstatus;
     private String cket;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;

    public Mpbahasamhs() {
    }

	
    public Mpbahasamhs(int id, Mmahasiswa mmahasiswa, String cno) {
        this.id = id;
        this.mmahasiswa = mmahasiswa;
        this.cno = cno;
    }
    public Mpbahasamhs(int id, Mmahasiswa mmahasiswa, String cno, String cnmbahasa, String cstatus, String cket, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby) {
       this.id = id;
       this.mmahasiswa = mmahasiswa;
       this.cno = cno;
       this.cnmbahasa = cnmbahasa;
       this.cstatus = cstatus;
       this.cket = cket;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mmahasiswa getMmahasiswa() {
        return this.mmahasiswa;
    }
    
    public void setMmahasiswa(Mmahasiswa mmahasiswa) {
        this.mmahasiswa = mmahasiswa;
    }
    public String getCno() {
        return this.cno;
    }
    
    public void setCno(String cno) {
        this.cno = cno;
    }
    public String getCnmbahasa() {
        return this.cnmbahasa;
    }
    
    public void setCnmbahasa(String cnmbahasa) {
        this.cnmbahasa = cnmbahasa;
    }
    public String getCstatus() {
        return this.cstatus;
    }
    
    public void setCstatus(String cstatus) {
        this.cstatus = cstatus;
    }
    public String getCket() {
        return this.cket;
    }
    
    public void setCket(String cket) {
        this.cket = cket;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }




}


