package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mpeminatan generated by hbm2java
 */
public class Mpeminatan  implements java.io.Serializable {


     private int id;
     private Mprodi mprodi;
     private String ckdminat;
     private String cnmminat;
     private String cnmminating;
     private String caktif;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;
     private Set<Mmahasiswa> mmahasiswas = new HashSet<Mmahasiswa>(0);

    public Mpeminatan() {
    }

	
    public Mpeminatan(int id, Mprodi mprodi, String ckdminat, String cnmminat) {
        this.id = id;
        this.mprodi = mprodi;
        this.ckdminat = ckdminat;
        this.cnmminat = cnmminat;
    }
    public Mpeminatan(int id, Mprodi mprodi, String ckdminat, String cnmminat, String cnmminating, String caktif, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby, Set<Mmahasiswa> mmahasiswas) {
       this.id = id;
       this.mprodi = mprodi;
       this.ckdminat = ckdminat;
       this.cnmminat = cnmminat;
       this.cnmminating = cnmminating;
       this.caktif = caktif;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
       this.mmahasiswas = mmahasiswas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mprodi getMprodi() {
        return this.mprodi;
    }
    
    public void setMprodi(Mprodi mprodi) {
        this.mprodi = mprodi;
    }
    public String getCkdminat() {
        return this.ckdminat;
    }
    
    public void setCkdminat(String ckdminat) {
        this.ckdminat = ckdminat;
    }
    public String getCnmminat() {
        return this.cnmminat;
    }
    
    public void setCnmminat(String cnmminat) {
        this.cnmminat = cnmminat;
    }
    public String getCnmminating() {
        return this.cnmminating;
    }
    
    public void setCnmminating(String cnmminating) {
        this.cnmminating = cnmminating;
    }
    public String getCaktif() {
        return this.caktif;
    }
    
    public void setCaktif(String caktif) {
        this.caktif = caktif;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }
    public Set<Mmahasiswa> getMmahasiswas() {
        return this.mmahasiswas;
    }
    
    public void setMmahasiswas(Set<Mmahasiswa> mmahasiswas) {
        this.mmahasiswas = mmahasiswas;
    }




}


