package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Mprestasimhs generated by hbm2java
 */
public class Mprestasimhs  implements java.io.Serializable {


     private int id;
     private int mahasiswaId;
     private String cno;
     private String cnmprestasi;
     private String cnmberi;
     private String cthnterima;
     private String cket;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;

    public Mprestasimhs() {
    }

	
    public Mprestasimhs(int id, int mahasiswaId, String cno) {
        this.id = id;
        this.mahasiswaId = mahasiswaId;
        this.cno = cno;
    }
    public Mprestasimhs(int id, int mahasiswaId, String cno, String cnmprestasi, String cnmberi
            , String cthnterima, String cket, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby) {
       this.id = id;
       this.mahasiswaId = mahasiswaId;
       this.cno = cno;
       this.cnmprestasi = cnmprestasi;
       this.cnmberi = cnmberi;
       this.cthnterima = cthnterima;
       this.cket = cket;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    public int getMahasiswaId() {
        return mahasiswaId;
    }

    public void setMahasiswaId(int mahasiswaId) {
        this.mahasiswaId = mahasiswaId;
    }

    public String getCno() {
        return this.cno;
    }
    
    public void setCno(String cno) {
        this.cno = cno;
    }
    public String getCnmprestasi() {
        return this.cnmprestasi;
    }
    
    public void setCnmprestasi(String cnmprestasi) {
        this.cnmprestasi = cnmprestasi;
    }
    public String getCnmberi() {
        return this.cnmberi;
    }
    
    public void setCnmberi(String cnmberi) {
        this.cnmberi = cnmberi;
    }
    public String getCthnterima() {
        return this.cthnterima;
    }
    
    public void setCthnterima(String cthnterima) {
        this.cthnterima = cthnterima;
    }
    public String getCket() {
        return this.cket;
    }
    
    public void setCket(String cket) {
        this.cket = cket;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }




}


