package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Msekolah generated by hbm2java
 */
public class Msekolah implements java.io.Serializable {


    private int id;
    private Mpegawai mpegawai;
    private Muniv muniv;
    private String ckdsekolah;
    private String cnamaSekolah;
    private String csingkatan;
    private String cnamaIng;
    private String visi;
    private String misi;
    private String noSk;
    private Date dcreateddate;
    private String ccreatedby;
    private Date dupdateddate;
    private String dupdatedby;
    private Set<Tabsenmhs> tabsenmhses = new HashSet<Tabsenmhs>(0);
    private Set<Tabsendosen> tabsendosens = new HashSet<Tabsendosen>(0);
    private Set<Thistkerja> thistkerjas = new HashSet<Thistkerja>(0);
    private Set<Mprodi> mprodis = new HashSet<Mprodi>(0);
    private Set<Tjadujian> tjadujians = new HashSet<Tjadujian>(0);
    private Set<Tjadkulmaster> tjadkulmasters = new HashSet<Tjadkulmaster>(0);
    private Set<Malumni> malumnis = new HashSet<Malumni>(0);
    private Set<Tlognilai> tlognilais = new HashSet<Tlognilai>(0);
    private Set<Msesikuliah> msesikuliahs = new HashSet<Msesikuliah>(0);
    private Set<Tpaketkuliah> tpaketkuliahs = new HashSet<Tpaketkuliah>(0);
    private Set<Tjadkuldetil> tjadkuldetils = new HashSet<Tjadkuldetil>(0);
    private Set<Tirspasca> tirspascas = new HashSet<Tirspasca>(0);
    private Set<Mcalakademik> mcalakademiks = new HashSet<Mcalakademik>(0);

    public Msekolah() {
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Muniv getMuniv() {
        return muniv;
    }

    public void setMuniv(Muniv muniv) {
        this.muniv = muniv;
    }

    public Mpegawai getMpegawai() {
        return this.mpegawai;
    }

    public void setMpegawai(Mpegawai mpegawai) {
        this.mpegawai = mpegawai;
    }

    public String getCkdsekolah() {
        return this.ckdsekolah;
    }

    public void setCkdsekolah(String ckdsekolah) {
        this.ckdsekolah = ckdsekolah;
    }

    public String getCnamaSekolah() {
        return this.cnamaSekolah;
    }

    public void setCnamaSekolah(String cnamaSekolah) {
        this.cnamaSekolah = cnamaSekolah;
    }

    public String getCsingkatan() {
        return this.csingkatan;
    }

    public void setCsingkatan(String csingkatan) {
        this.csingkatan = csingkatan;
    }

    public String getCnamaIng() {
        return this.cnamaIng;
    }

    public void setCnamaIng(String cnamaIng) {
        this.cnamaIng = cnamaIng;
    }

    public String getVisi() {
        return this.visi;
    }

    public void setVisi(String visi) {
        this.visi = visi;
    }

    public String getMisi() {
        return this.misi;
    }

    public void setMisi(String misi) {
        this.misi = misi;
    }

    public String getNoSk() {
        return this.noSk;
    }

    public void setNoSk(String noSk) {
        this.noSk = noSk;
    }

    public Date getDcreateddate() {
        return this.dcreateddate;
    }

    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }

    public String getCcreatedby() {
        return this.ccreatedby;
    }

    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }

    public Date getDupdateddate() {
        return this.dupdateddate;
    }

    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }

    public String getDupdatedby() {
        return this.dupdatedby;
    }

    public void setDupdatedby(String dupdatedby) {
        this.dupdatedby = dupdatedby;
    }

    public Set<Tabsenmhs> getTabsenmhses() {
        return this.tabsenmhses;
    }

    public void setTabsenmhses(Set<Tabsenmhs> tabsenmhses) {
        this.tabsenmhses = tabsenmhses;
    }

    public Set<Tabsendosen> getTabsendosens() {
        return this.tabsendosens;
    }

    public void setTabsendosens(Set<Tabsendosen> tabsendosens) {
        this.tabsendosens = tabsendosens;
    }

    public Set<Thistkerja> getThistkerjas() {
        return this.thistkerjas;
    }

    public void setThistkerjas(Set<Thistkerja> thistkerjas) {
        this.thistkerjas = thistkerjas;
    }

    public Set<Mprodi> getMprodis() {
        return this.mprodis;
    }

    public void setMprodis(Set<Mprodi> mprodis) {
        this.mprodis = mprodis;
    }

    public Set<Tjadujian> getTjadujians() {
        return this.tjadujians;
    }

    public void setTjadujians(Set<Tjadujian> tjadujians) {
        this.tjadujians = tjadujians;
    }

    public Set<Tjadkulmaster> getTjadkulmasters() {
        return this.tjadkulmasters;
    }

    public void setTjadkulmasters(Set<Tjadkulmaster> tjadkulmasters) {
        this.tjadkulmasters = tjadkulmasters;
    }

    public Set<Malumni> getMalumnis() {
        return this.malumnis;
    }

    public void setMalumnis(Set<Malumni> malumnis) {
        this.malumnis = malumnis;
    }

    public Set<Tlognilai> getTlognilais() {
        return this.tlognilais;
    }

    public void setTlognilais(Set<Tlognilai> tlognilais) {
        this.tlognilais = tlognilais;
    }

    public Set<Msesikuliah> getMsesikuliahs() {
        return this.msesikuliahs;
    }

    public void setMsesikuliahs(Set<Msesikuliah> msesikuliahs) {
        this.msesikuliahs = msesikuliahs;
    }

    public Set<Tpaketkuliah> getTpaketkuliahs() {
        return this.tpaketkuliahs;
    }

    public void setTpaketkuliahs(Set<Tpaketkuliah> tpaketkuliahs) {
        this.tpaketkuliahs = tpaketkuliahs;
    }

    public Set<Tjadkuldetil> getTjadkuldetils() {
        return this.tjadkuldetils;
    }

    public void setTjadkuldetils(Set<Tjadkuldetil> tjadkuldetils) {
        this.tjadkuldetils = tjadkuldetils;
    }

    public Set<Tirspasca> getTirspascas() {
        return this.tirspascas;
    }

    public void setTirspascas(Set<Tirspasca> tirspascas) {
        this.tirspascas = tirspascas;
    }

    public Set<Mcalakademik> getMcalakademiks() {
        return this.mcalakademiks;
    }

    public void setMcalakademiks(Set<Mcalakademik> mcalakademiks) {
        this.mcalakademiks = mcalakademiks;
    }


}


