package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Msesikuliah generated by hbm2java
 */
public class Msesikuliah  implements java.io.Serializable {


     private int id;
     private Msekolah msekolah;
     private String ckdsesi;
     private String cjamawal;
     private String cjamakhir;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;
     private Set<Tjadkuldetil> tjadkuldetils = new HashSet<Tjadkuldetil>(0);
     private Set<Tjadujian> tjadujians = new HashSet<Tjadujian>(0);
     private Set<Tabsendosen> tabsendosens = new HashSet<Tabsendosen>(0);
     private Set<Tabsenmhs> tabsenmhses = new HashSet<Tabsenmhs>(0);

    public Msesikuliah() {
    }

	
    public Msesikuliah(int id, Msekolah msekolah, String ckdsesi) {
        this.id = id;
        this.msekolah = msekolah;
        this.ckdsesi = ckdsesi;
    }
    public Msesikuliah(int id, Msekolah msekolah, String ckdsesi, String cjamawal, String cjamakhir, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby, Set<Tjadkuldetil> tjadkuldetils, Set<Tjadujian> tjadujians, Set<Tabsendosen> tabsendosens, Set<Tabsenmhs> tabsenmhses) {
       this.id = id;
       this.msekolah = msekolah;
       this.ckdsesi = ckdsesi;
       this.cjamawal = cjamawal;
       this.cjamakhir = cjamakhir;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
       this.tjadkuldetils = tjadkuldetils;
       this.tjadujians = tjadujians;
       this.tabsendosens = tabsendosens;
       this.tabsenmhses = tabsenmhses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Msekolah getMsekolah() {
        return this.msekolah;
    }
    
    public void setMsekolah(Msekolah msekolah) {
        this.msekolah = msekolah;
    }
    public String getCkdsesi() {
        return this.ckdsesi;
    }
    
    public void setCkdsesi(String ckdsesi) {
        this.ckdsesi = ckdsesi;
    }
    public String getCjamawal() {
        return this.cjamawal;
    }
    
    public void setCjamawal(String cjamawal) {
        this.cjamawal = cjamawal;
    }
    public String getCjamakhir() {
        return this.cjamakhir;
    }
    
    public void setCjamakhir(String cjamakhir) {
        this.cjamakhir = cjamakhir;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }
    public Set<Tjadkuldetil> getTjadkuldetils() {
        return this.tjadkuldetils;
    }
    
    public void setTjadkuldetils(Set<Tjadkuldetil> tjadkuldetils) {
        this.tjadkuldetils = tjadkuldetils;
    }
    public Set<Tjadujian> getTjadujians() {
        return this.tjadujians;
    }
    
    public void setTjadujians(Set<Tjadujian> tjadujians) {
        this.tjadujians = tjadujians;
    }
    public Set<Tabsendosen> getTabsendosens() {
        return this.tabsendosens;
    }
    
    public void setTabsendosens(Set<Tabsendosen> tabsendosens) {
        this.tabsendosens = tabsendosens;
    }
    public Set<Tabsenmhs> getTabsenmhses() {
        return this.tabsenmhses;
    }
    
    public void setTabsenmhses(Set<Tabsenmhs> tabsenmhses) {
        this.tabsenmhses = tabsenmhses;
    }




}


