package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Mstatusmhs generated by hbm2java
 */
public class Mstatusmhs  implements java.io.Serializable {
	//public static String ID = "id";
    //public static String CODE = "ckdstatmhs";
    //public static String NAME = "cnmstatmhs";
    //public static String KETERANGAN = "cketerangan";

     private int id;
     private String ckdstatmhs;
     private String cnmstatmhs;
     private String cketerangan;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;

    public Mstatusmhs() {
    }

	
    public Mstatusmhs(int id, String ckdstatmhs) {
        this.id = id;
        this.ckdstatmhs = ckdstatmhs;
    }
    public Mstatusmhs(int id, String ckdstatmhs, String cnmstatmhs, String cketerangan, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby) {
       this.id = id;
       this.ckdstatmhs = ckdstatmhs;
       this.cnmstatmhs = cnmstatmhs;
       this.cketerangan = cketerangan;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCkdstatmhs() {
        return this.ckdstatmhs;
    }
    
    public void setCkdstatmhs(String ckdstatmhs) {
        this.ckdstatmhs = ckdstatmhs;
    }
    public String getCnmstatmhs() {
        return this.cnmstatmhs;
    }
    
    public void setCnmstatmhs(String cnmstatmhs) {
        this.cnmstatmhs = cnmstatmhs;
    }
    public String getCketerangan() {
        return this.cketerangan;
    }
    
    public void setCketerangan(String cketerangan) {
        this.cketerangan = cketerangan;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }




}


