package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mtbmtkl generated by hbm2java
 */
public class Mtbmtkl  implements java.io.Serializable {


     private int id;
     private String ckdmtk;
     private String cnamamk;
     private String cingmk;
     private String csingmk;
     private Integer nsks;
     private String keterangan;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;
     private Set<Tjadkuldetil> tjadkuldetils = new HashSet<Tjadkuldetil>(0);
     private Set<Tabsenmhs> tabsenmhses = new HashSet<Tabsenmhs>(0);
     private Set<Tjadkulmaster> tjadkulmasters = new HashSet<Tjadkulmaster>(0);
     private Set<Tirspasca> tirspascas = new HashSet<Tirspasca>(0);
     private Set<Tlognilai> tlognilais = new HashSet<Tlognilai>(0);
     private Set<Tabsendosen> tabsendosens = new HashSet<Tabsendosen>(0);
     private Set<Tpaketkuliah> tpaketkuliahs = new HashSet<Tpaketkuliah>(0);
     private Set<Tjadujian> tjadujians = new HashSet<Tjadujian>(0);
     private Set<Mdetilkurikulum> mdetilkurikulums = new HashSet<Mdetilkurikulum>(0);

    public Mtbmtkl() {
    }

	
    public Mtbmtkl(int id, String ckdmtk, String cnamamk, String cingmk) {
        this.id = id;
        this.ckdmtk = ckdmtk;
        this.cnamamk = cnamamk;
        this.cingmk = cingmk;
    }
    public Mtbmtkl(int id, String ckdmtk, String cnamamk, String cingmk, String csingmk, Integer nsks, String keterangan, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby, Set<Tjadkuldetil> tjadkuldetils, Set<Tabsenmhs> tabsenmhses, Set<Tjadkulmaster> tjadkulmasters, Set<Tirspasca> tirspascas, Set<Tlognilai> tlognilais, Set<Tabsendosen> tabsendosens, Set<Tpaketkuliah> tpaketkuliahs, Set<Tjadujian> tjadujians, Set<Mdetilkurikulum> mdetilkurikulums) {
       this.id = id;
       this.ckdmtk = ckdmtk;
       this.cnamamk = cnamamk;
       this.cingmk = cingmk;
       this.csingmk = csingmk;
       this.nsks = nsks;
       this.keterangan = keterangan;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
       this.tjadkuldetils = tjadkuldetils;
       this.tabsenmhses = tabsenmhses;
       this.tjadkulmasters = tjadkulmasters;
       this.tirspascas = tirspascas;
       this.tlognilais = tlognilais;
       this.tabsendosens = tabsendosens;
       this.tpaketkuliahs = tpaketkuliahs;
       this.tjadujians = tjadujians;
       this.mdetilkurikulums = mdetilkurikulums;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCkdmtk() {
        return this.ckdmtk;
    }
    
    public void setCkdmtk(String ckdmtk) {
        this.ckdmtk = ckdmtk;
    }
    public String getCnamamk() {
        return this.cnamamk;
    }
    
    public void setCnamamk(String cnamamk) {
        this.cnamamk = cnamamk;
    }
    public String getCingmk() {
        return this.cingmk;
    }
    
    public void setCingmk(String cingmk) {
        this.cingmk = cingmk;
    }
    public String getCsingmk() {
        return this.csingmk;
    }
    
    public void setCsingmk(String csingmk) {
        this.csingmk = csingmk;
    }
    public Integer getNsks() {
        return this.nsks;
    }
    
    public void setNsks(Integer nsks) {
        this.nsks = nsks;
    }
    public String getKeterangan() {
        return this.keterangan;
    }
    
    public void setKeterangan(String keterangan) {
        this.keterangan = keterangan;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }
    public Set<Tjadkuldetil> getTjadkuldetils() {
        return this.tjadkuldetils;
    }
    
    public void setTjadkuldetils(Set<Tjadkuldetil> tjadkuldetils) {
        this.tjadkuldetils = tjadkuldetils;
    }
    public Set<Tabsenmhs> getTabsenmhses() {
        return this.tabsenmhses;
    }
    
    public void setTabsenmhses(Set<Tabsenmhs> tabsenmhses) {
        this.tabsenmhses = tabsenmhses;
    }
    public Set<Tjadkulmaster> getTjadkulmasters() {
        return this.tjadkulmasters;
    }
    
    public void setTjadkulmasters(Set<Tjadkulmaster> tjadkulmasters) {
        this.tjadkulmasters = tjadkulmasters;
    }
    public Set<Tirspasca> getTirspascas() {
        return this.tirspascas;
    }
    
    public void setTirspascas(Set<Tirspasca> tirspascas) {
        this.tirspascas = tirspascas;
    }
    public Set<Tlognilai> getTlognilais() {
        return this.tlognilais;
    }
    
    public void setTlognilais(Set<Tlognilai> tlognilais) {
        this.tlognilais = tlognilais;
    }
    public Set<Tabsendosen> getTabsendosens() {
        return this.tabsendosens;
    }
    
    public void setTabsendosens(Set<Tabsendosen> tabsendosens) {
        this.tabsendosens = tabsendosens;
    }
    public Set<Tpaketkuliah> getTpaketkuliahs() {
        return this.tpaketkuliahs;
    }
    
    public void setTpaketkuliahs(Set<Tpaketkuliah> tpaketkuliahs) {
        this.tpaketkuliahs = tpaketkuliahs;
    }
    public Set<Tjadujian> getTjadujians() {
        return this.tjadujians;
    }
    
    public void setTjadujians(Set<Tjadujian> tjadujians) {
        this.tjadujians = tjadujians;
    }
    public Set<Mdetilkurikulum> getMdetilkurikulums() {
        return this.mdetilkurikulums;
    }
    
    public void setMdetilkurikulums(Set<Mdetilkurikulum> mdetilkurikulums) {
        this.mdetilkurikulums = mdetilkurikulums;
    }




}


