package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Mterm generated by hbm2java
 */
public class Mterm implements java.io.Serializable {


    private int id;
    private String kdTerm;
    private String deskripsi;
    private String ccreatedby;
    private Date dcreateddate;
    private String cupdatedby;
    private Date dupdateddate;
    private Date dtglmulai;
    private Date dtglakhir;
    private Mthajar mthajar;

    public Mterm() {
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getKdTerm() {
        return this.kdTerm;
    }

    public void setKdTerm(String kdTerm) {
        this.kdTerm = kdTerm;
    }

    public String getDeskripsi() {
        return this.deskripsi;
    }

    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi;
    }

    public String getCcreatedby() {
        return this.ccreatedby;
    }

    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }

    public Date getDcreateddate() {
        return this.dcreateddate;
    }

    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }

    public String getCupdatedby() {
        return this.cupdatedby;
    }

    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }

    public Date getDupdateddate() {
        return this.dupdateddate;
    }

    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }

    public Date getDtglmulai() {
        return dtglmulai;
    }

    public void setDtglmulai(Date dtglmulai) {
        this.dtglmulai = dtglmulai;
    }

    public Date getDtglakhir() {
        return dtglakhir;
    }

    public void setDtglakhir(Date dtglakhir) {
        this.dtglakhir = dtglakhir;
    }

    public Mthajar getMthajar() {
        return mthajar;
    }

    public void setMthajar(Mthajar mthajar) {
        this.mthajar = mthajar;
    }
}


