package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Muniv generated by hbm2java
 */
public class Muniv  implements java.io.Serializable {


     private int id;
     private String ckdUniv;
     private String cnamaUniv;
     private String alamatUniv;
     private char cstatus;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;
     private Set<Mhistpnddkmhs> mhistpnddkmhses = new HashSet<Mhistpnddkmhs>(0);

    public Muniv() {
    }

	
    public Muniv(int id, String ckdUniv, String cnamaUniv, String alamatUniv, char cstatus) {
        this.id = id;
        this.ckdUniv = ckdUniv;
        this.cnamaUniv = cnamaUniv;
        this.alamatUniv = alamatUniv;
        this.cstatus = cstatus;
    }
    public Muniv(int id, String ckdUniv, String cnamaUniv, String alamatUniv, char cstatus, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby, Set<Mhistpnddkmhs> mhistpnddkmhses) {
       this.id = id;
       this.ckdUniv = ckdUniv;
       this.cnamaUniv = cnamaUniv;
       this.alamatUniv = alamatUniv;
       this.cstatus = cstatus;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
       this.mhistpnddkmhses = mhistpnddkmhses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCkdUniv() {
        return this.ckdUniv;
    }
    
    public void setCkdUniv(String ckdUniv) {
        this.ckdUniv = ckdUniv;
    }
    public String getCnamaUniv() {
        return this.cnamaUniv;
    }
    
    public void setCnamaUniv(String cnamaUniv) {
        this.cnamaUniv = cnamaUniv;
    }
    public String getAlamatUniv() {
        return this.alamatUniv;
    }
    
    public void setAlamatUniv(String alamatUniv) {
        this.alamatUniv = alamatUniv;
    }
    public char getCstatus() {
        return this.cstatus;
    }
    
    public void setCstatus(char cstatus) {
        this.cstatus = cstatus;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }
    public Set<Mhistpnddkmhs> getMhistpnddkmhses() {
        return this.mhistpnddkmhses;
    }
    
    public void setMhistpnddkmhses(Set<Mhistpnddkmhs> mhistpnddkmhses) {
        this.mhistpnddkmhses = mhistpnddkmhses;
    }




}


