package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tabsenmhs generated by hbm2java
 */
public class Tabsenmhs  implements java.io.Serializable {


     private int id;
     private Msekolah msekolah;
     private Mprodi mprodi;
     private Mmahasiswa mmahasiswa;
     private Mtbmtkl mtbmtkl;
     private Msesikuliah msesikuliah;
     private Mhari mhari;
     private String cterm;
     private String ckelompok;
     private Date dtglkul;
     private String cabsen;
     private String cpertemuan;
     private String cthajar;
     private String csmt;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;

    public Tabsenmhs() {
    }

	
    public Tabsenmhs(int id, Msekolah msekolah, Mprodi mprodi, Mmahasiswa mmahasiswa, Mtbmtkl mtbmtkl, Msesikuliah msesikuliah, Mhari mhari, String cterm, String ckelompok, Date dtglkul) {
        this.id = id;
        this.msekolah = msekolah;
        this.mprodi = mprodi;
        this.mmahasiswa = mmahasiswa;
        this.mtbmtkl = mtbmtkl;
        this.msesikuliah = msesikuliah;
        this.mhari = mhari;
        this.cterm = cterm;
        this.ckelompok = ckelompok;
        this.dtglkul = dtglkul;
    }
    public Tabsenmhs(int id, Msekolah msekolah, Mprodi mprodi, Mmahasiswa mmahasiswa, Mtbmtkl mtbmtkl, Msesikuliah msesikuliah, Mhari mhari, String cterm, String ckelompok, Date dtglkul, String cabsen, String cpertemuan, String cthajar, String csmt, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby) {
       this.id = id;
       this.msekolah = msekolah;
       this.mprodi = mprodi;
       this.mmahasiswa = mmahasiswa;
       this.mtbmtkl = mtbmtkl;
       this.msesikuliah = msesikuliah;
       this.mhari = mhari;
       this.cterm = cterm;
       this.ckelompok = ckelompok;
       this.dtglkul = dtglkul;
       this.cabsen = cabsen;
       this.cpertemuan = cpertemuan;
       this.cthajar = cthajar;
       this.csmt = csmt;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Msekolah getMsekolah() {
        return this.msekolah;
    }
    
    public void setMsekolah(Msekolah msekolah) {
        this.msekolah = msekolah;
    }
    public Mprodi getMprodi() {
        return this.mprodi;
    }
    
    public void setMprodi(Mprodi mprodi) {
        this.mprodi = mprodi;
    }
    public Mmahasiswa getMmahasiswa() {
        return this.mmahasiswa;
    }
    
    public void setMmahasiswa(Mmahasiswa mmahasiswa) {
        this.mmahasiswa = mmahasiswa;
    }
    public Mtbmtkl getMtbmtkl() {
        return this.mtbmtkl;
    }
    
    public void setMtbmtkl(Mtbmtkl mtbmtkl) {
        this.mtbmtkl = mtbmtkl;
    }
    public Msesikuliah getMsesikuliah() {
        return this.msesikuliah;
    }
    
    public void setMsesikuliah(Msesikuliah msesikuliah) {
        this.msesikuliah = msesikuliah;
    }
    public Mhari getMhari() {
        return this.mhari;
    }
    
    public void setMhari(Mhari mhari) {
        this.mhari = mhari;
    }
    public String getCterm() {
        return this.cterm;
    }
    
    public void setCterm(String cterm) {
        this.cterm = cterm;
    }
    public String getCkelompok() {
        return this.ckelompok;
    }
    
    public void setCkelompok(String ckelompok) {
        this.ckelompok = ckelompok;
    }
    public Date getDtglkul() {
        return this.dtglkul;
    }
    
    public void setDtglkul(Date dtglkul) {
        this.dtglkul = dtglkul;
    }
    public String getCabsen() {
        return this.cabsen;
    }
    
    public void setCabsen(String cabsen) {
        this.cabsen = cabsen;
    }
    public String getCpertemuan() {
        return this.cpertemuan;
    }
    
    public void setCpertemuan(String cpertemuan) {
        this.cpertemuan = cpertemuan;
    }
    public String getCthajar() {
        return this.cthajar;
    }
    
    public void setCthajar(String cthajar) {
        this.cthajar = cthajar;
    }
    public String getCsmt() {
        return this.csmt;
    }
    
    public void setCsmt(String csmt) {
        this.csmt = csmt;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }




}


