package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tdaftarwisuda generated by hbm2java
 */
public class Tdaftarwisuda  implements java.io.Serializable {


     private int nrecid;
     private String ckdsekolah;
     private String ckdprogst;
     private String cterm;
     private String cthajar;
     private String csmt;
     private String cnim;
     private Date dtgldaftar;
     private String ccreatedby;
     private Date dcreateddate;
     private String cupdatedby;
     private Date dupdateddate;

    public Tdaftarwisuda() {
    }

	
    public Tdaftarwisuda(int nrecid, String ckdsekolah, String ckdprogst, String cterm, String cnim) {
        this.nrecid = nrecid;
        this.ckdsekolah = ckdsekolah;
        this.ckdprogst = ckdprogst;
        this.cterm = cterm;
        this.cnim = cnim;
    }
    public Tdaftarwisuda(int nrecid, String ckdsekolah, String ckdprogst, String cterm, String cthajar, String csmt, String cnim, Date dtgldaftar, String ccreatedby, Date dcreateddate, String cupdatedby, Date dupdateddate) {
       this.nrecid = nrecid;
       this.ckdsekolah = ckdsekolah;
       this.ckdprogst = ckdprogst;
       this.cterm = cterm;
       this.cthajar = cthajar;
       this.csmt = csmt;
       this.cnim = cnim;
       this.dtgldaftar = dtgldaftar;
       this.ccreatedby = ccreatedby;
       this.dcreateddate = dcreateddate;
       this.cupdatedby = cupdatedby;
       this.dupdateddate = dupdateddate;
    }
   
    public int getNrecid() {
        return this.nrecid;
    }
    
    public void setNrecid(int nrecid) {
        this.nrecid = nrecid;
    }
    public String getCkdsekolah() {
        return this.ckdsekolah;
    }
    
    public void setCkdsekolah(String ckdsekolah) {
        this.ckdsekolah = ckdsekolah;
    }
    public String getCkdprogst() {
        return this.ckdprogst;
    }
    
    public void setCkdprogst(String ckdprogst) {
        this.ckdprogst = ckdprogst;
    }
    public String getCterm() {
        return this.cterm;
    }
    
    public void setCterm(String cterm) {
        this.cterm = cterm;
    }
    public String getCthajar() {
        return this.cthajar;
    }
    
    public void setCthajar(String cthajar) {
        this.cthajar = cthajar;
    }
    public String getCsmt() {
        return this.csmt;
    }
    
    public void setCsmt(String csmt) {
        this.csmt = csmt;
    }
    public String getCnim() {
        return this.cnim;
    }
    
    public void setCnim(String cnim) {
        this.cnim = cnim;
    }
    public Date getDtgldaftar() {
        return this.dtgldaftar;
    }
    
    public void setDtgldaftar(Date dtgldaftar) {
        this.dtgldaftar = dtgldaftar;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }




}


