package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tfeedbackkuliah generated by hbm2java
 */
public class Tfeedbackkuliah  implements java.io.Serializable {


     private int id;
     private String cterm;
     private int sekolahId;
     private int prodiId;
     private String ckelompok;
     private int matakuliahId;
     private int irsId;
     private int mahasiswaId;
     private String ckdfeedback;
     private int nnopertanyaan;
     private String jawaban;
     private String ccreatedby;
     private Date dcreateddate;
     private String cupdatedby;
     private Date dupdateddate;

    public Tfeedbackkuliah() {
    }

	
    public Tfeedbackkuliah(int id, String cterm, int sekolahId, int prodiId, String ckelompok, int matakuliahId, int irsId, int mahasiswaId, String ckdfeedback, int nnopertanyaan) {
        this.id = id;
        this.cterm = cterm;
        this.sekolahId = sekolahId;
        this.prodiId = prodiId;
        this.ckelompok = ckelompok;
        this.matakuliahId = matakuliahId;
        this.irsId = irsId;
        this.mahasiswaId = mahasiswaId;
        this.ckdfeedback = ckdfeedback;
        this.nnopertanyaan = nnopertanyaan;
    }
    public Tfeedbackkuliah(int id, String cterm, int sekolahId, int prodiId, String ckelompok, int matakuliahId, int irsId, int mahasiswaId, String ckdfeedback, int nnopertanyaan, String jawaban, String ccreatedby, Date dcreateddate, String cupdatedby, Date dupdateddate) {
       this.id = id;
       this.cterm = cterm;
       this.sekolahId = sekolahId;
       this.prodiId = prodiId;
       this.ckelompok = ckelompok;
       this.matakuliahId = matakuliahId;
       this.irsId = irsId;
       this.mahasiswaId = mahasiswaId;
       this.ckdfeedback = ckdfeedback;
       this.nnopertanyaan = nnopertanyaan;
       this.jawaban = jawaban;
       this.ccreatedby = ccreatedby;
       this.dcreateddate = dcreateddate;
       this.cupdatedby = cupdatedby;
       this.dupdateddate = dupdateddate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCterm() {
        return this.cterm;
    }
    
    public void setCterm(String cterm) {
        this.cterm = cterm;
    }
    public int getSekolahId() {
        return this.sekolahId;
    }
    
    public void setSekolahId(int sekolahId) {
        this.sekolahId = sekolahId;
    }
    public int getProdiId() {
        return this.prodiId;
    }
    
    public void setProdiId(int prodiId) {
        this.prodiId = prodiId;
    }
    public String getCkelompok() {
        return this.ckelompok;
    }
    
    public void setCkelompok(String ckelompok) {
        this.ckelompok = ckelompok;
    }
    public int getMatakuliahId() {
        return this.matakuliahId;
    }
    
    public void setMatakuliahId(int matakuliahId) {
        this.matakuliahId = matakuliahId;
    }
    public int getIrsId() {
        return this.irsId;
    }
    
    public void setIrsId(int irsId) {
        this.irsId = irsId;
    }
    public int getMahasiswaId() {
        return this.mahasiswaId;
    }
    
    public void setMahasiswaId(int mahasiswaId) {
        this.mahasiswaId = mahasiswaId;
    }
    public String getCkdfeedback() {
        return this.ckdfeedback;
    }
    
    public void setCkdfeedback(String ckdfeedback) {
        this.ckdfeedback = ckdfeedback;
    }
    public int getNnopertanyaan() {
        return this.nnopertanyaan;
    }
    
    public void setNnopertanyaan(int nnopertanyaan) {
        this.nnopertanyaan = nnopertanyaan;
    }
    public String getJawaban() {
        return this.jawaban;
    }
    
    public void setJawaban(String jawaban) {
        this.jawaban = jawaban;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }




}


