package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tjadujian generated by hbm2java
 */
public class Tjadujian  implements java.io.Serializable {


     private int id;
     private Mruang mruang;
     private Msekolah msekolah;
     private Mprodi mprodi;
     private Mtbmtkl mtbmtkl;
     private Msesikuliah msesikuliah;
     private Mhari mhari;
     private String cterm;
     private String ckelompok;
     private Date dtgluji;
     private Integer njmlsesi;
     private Integer nmaks;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;

    public Tjadujian() {
    }

	
    public Tjadujian(int id, Mruang mruang, Msekolah msekolah, Mprodi mprodi, Mtbmtkl mtbmtkl, Msesikuliah msesikuliah, Mhari mhari, String cterm, String ckelompok) {
        this.id = id;
        this.mruang = mruang;
        this.msekolah = msekolah;
        this.mprodi = mprodi;
        this.mtbmtkl = mtbmtkl;
        this.msesikuliah = msesikuliah;
        this.mhari = mhari;
        this.cterm = cterm;
        this.ckelompok = ckelompok;
    }
    public Tjadujian(int id, Mruang mruang, Msekolah msekolah, Mprodi mprodi, Mtbmtkl mtbmtkl, Msesikuliah msesikuliah, Mhari mhari, String cterm, String ckelompok, Date dtgluji, Integer njmlsesi, Integer nmaks, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby) {
       this.id = id;
       this.mruang = mruang;
       this.msekolah = msekolah;
       this.mprodi = mprodi;
       this.mtbmtkl = mtbmtkl;
       this.msesikuliah = msesikuliah;
       this.mhari = mhari;
       this.cterm = cterm;
       this.ckelompok = ckelompok;
       this.dtgluji = dtgluji;
       this.njmlsesi = njmlsesi;
       this.nmaks = nmaks;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mruang getMruang() {
        return this.mruang;
    }
    
    public void setMruang(Mruang mruang) {
        this.mruang = mruang;
    }
    public Msekolah getMsekolah() {
        return this.msekolah;
    }
    
    public void setMsekolah(Msekolah msekolah) {
        this.msekolah = msekolah;
    }
    public Mprodi getMprodi() {
        return this.mprodi;
    }
    
    public void setMprodi(Mprodi mprodi) {
        this.mprodi = mprodi;
    }
    public Mtbmtkl getMtbmtkl() {
        return this.mtbmtkl;
    }
    
    public void setMtbmtkl(Mtbmtkl mtbmtkl) {
        this.mtbmtkl = mtbmtkl;
    }
    public Msesikuliah getMsesikuliah() {
        return this.msesikuliah;
    }
    
    public void setMsesikuliah(Msesikuliah msesikuliah) {
        this.msesikuliah = msesikuliah;
    }
    public Mhari getMhari() {
        return this.mhari;
    }
    
    public void setMhari(Mhari mhari) {
        this.mhari = mhari;
    }
    public String getCterm() {
        return this.cterm;
    }
    
    public void setCterm(String cterm) {
        this.cterm = cterm;
    }
    public String getCkelompok() {
        return this.ckelompok;
    }
    
    public void setCkelompok(String ckelompok) {
        this.ckelompok = ckelompok;
    }
    public Date getDtgluji() {
        return this.dtgluji;
    }
    
    public void setDtgluji(Date dtgluji) {
        this.dtgluji = dtgluji;
    }
    public Integer getNjmlsesi() {
        return this.njmlsesi;
    }
    
    public void setNjmlsesi(Integer njmlsesi) {
        this.njmlsesi = njmlsesi;
    }
    public Integer getNmaks() {
        return this.nmaks;
    }
    
    public void setNmaks(Integer nmaks) {
        this.nmaks = nmaks;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }




}


