package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tpaketkuliah generated by hbm2java
 */
public class Tpaketkuliah  implements java.io.Serializable {


     private int id;
     private Msekolah msekolah;
     private Mprodi mprodi;
     private Mtbmtkl mtbmtkl;
     private String cterm;
     private String cthajar;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;

    public Tpaketkuliah() {
    }

	
    public Tpaketkuliah(int id, Msekolah msekolah, Mprodi mprodi, Mtbmtkl mtbmtkl, String cterm) {
        this.id = id;
        this.msekolah = msekolah;
        this.mprodi = mprodi;
        this.mtbmtkl = mtbmtkl;
        this.cterm = cterm;
    }
    public Tpaketkuliah(int id, Msekolah msekolah, Mprodi mprodi, Mtbmtkl mtbmtkl, String cterm, String cthajar, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby) {
       this.id = id;
       this.msekolah = msekolah;
       this.mprodi = mprodi;
       this.mtbmtkl = mtbmtkl;
       this.cterm = cterm;
       this.cthajar = cthajar;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Msekolah getMsekolah() {
        return this.msekolah;
    }
    
    public void setMsekolah(Msekolah msekolah) {
        this.msekolah = msekolah;
    }
    public Mprodi getMprodi() {
        return this.mprodi;
    }
    
    public void setMprodi(Mprodi mprodi) {
        this.mprodi = mprodi;
    }
    public Mtbmtkl getMtbmtkl() {
        return this.mtbmtkl;
    }
    
    public void setMtbmtkl(Mtbmtkl mtbmtkl) {
        this.mtbmtkl = mtbmtkl;
    }
    public String getCterm() {
        return this.cterm;
    }
    
    public void setCterm(String cterm) {
        this.cterm = cterm;
    }
    public String getCthajar() {
        return this.cthajar;
    }
    
    public void setCthajar(String cthajar) {
        this.cthajar = cthajar;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }




}


