package id.ac.idu.backend.model;
// Generated 06 Mar 12 10:03:27 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AppNews generated by hbm2java
 */
public class AppNews implements java.io.Serializable {


    private int anwId;
    private int version;
    private String anwText;
    private Date anwDate;
    private Set<Malumni> malumnis = new HashSet<Malumni>(0);

    public AppNews() {
    }


    public AppNews(int anwId, Date anwDate) {
        this.anwId = anwId;
        this.anwDate = anwDate;
    }

    public AppNews(int anwId, String anwText, Date anwDate) {
        this.anwId = anwId;
        this.anwText = anwText;
        this.anwDate = anwDate;
    }

    public int getAnwId() {
        return this.anwId;
    }

    public void setAnwId(int anwId) {
        this.anwId = anwId;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getAnwText() {
        return this.anwText;
    }

    public void setAnwText(String anwText) {
        this.anwText = anwText;
    }

    public Date getAnwDate() {
        return this.anwDate;
    }

    public void setAnwDate(Date anwDate) {
        this.anwDate = anwDate;
    }

    public Set<Malumni> getMalumnis() {
        return this.malumnis;
    }

    public void setMalumnis(Set<Malumni> malumnis) {
        this.malumnis = malumnis;
    }


}


