package id.ac.idu.backend.model;
// Generated 06 Mar 12 10:03:27 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Artikel generated by hbm2java
 */
public class Artikel implements java.io.Serializable {


    private int artId;
    private int version;
    private String artKurzbezeichnung;
    private String artLangbezeichnung;
    private String artNr;
    private BigDecimal artPreis;
    private Set<Auftragposition> auftragpositions = new HashSet<Auftragposition>(0);

    public Artikel() {
    }


    public Artikel(int artId, String artKurzbezeichnung, String artNr, BigDecimal artPreis) {
        this.artId = artId;
        this.artKurzbezeichnung = artKurzbezeichnung;
        this.artNr = artNr;
        this.artPreis = artPreis;
    }

    public Artikel(int artId, String artKurzbezeichnung, String artLangbezeichnung, String artNr, BigDecimal artPreis, Set<Auftragposition> auftragpositions) {
        this.artId = artId;
        this.artKurzbezeichnung = artKurzbezeichnung;
        this.artLangbezeichnung = artLangbezeichnung;
        this.artNr = artNr;
        this.artPreis = artPreis;
        this.auftragpositions = auftragpositions;
    }

    public int getArtId() {
        return this.artId;
    }

    public void setArtId(int artId) {
        this.artId = artId;
    }

    public int getVersion() {
        return this.version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getArtKurzbezeichnung() {
        return this.artKurzbezeichnung;
    }

    public void setArtKurzbezeichnung(String artKurzbezeichnung) {
        this.artKurzbezeichnung = artKurzbezeichnung;
    }

    public String getArtLangbezeichnung() {
        return this.artLangbezeichnung;
    }

    public void setArtLangbezeichnung(String artLangbezeichnung) {
        this.artLangbezeichnung = artLangbezeichnung;
    }

    public String getArtNr() {
        return this.artNr;
    }

    public void setArtNr(String artNr) {
        this.artNr = artNr;
    }

    public BigDecimal getArtPreis() {
        return this.artPreis;
    }

    public void setArtPreis(BigDecimal artPreis) {
        this.artPreis = artPreis;
    }

    public Set<Auftragposition> getAuftragpositions() {
        return this.auftragpositions;
    }

    public void setAuftragpositions(Set<Auftragposition> auftragpositions) {
        this.auftragpositions = auftragpositions;
    }


}


