package id.ac.idu.backend.model;
// Generated 06 Mar 12 10:03:27 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Mcalakademik generated by hbm2java
 */
public class Mcalakademik implements java.io.Serializable {


    private int id;
    private Msekolah msekolah;
    private Mprodi mprodi;
    private Mkegiatan mkegiatan;
    private String cno;
    private Date dtglawal;
    private Date dtglakhir;
    private String cjamawal;
    private String cjamakhir;
    private String ckdkgt;
    private String cterm;
    private String cthajar;
    private String csmt;
    private Date dcreateddate;
    private String ccreatedby;
    private Date dupdateddate;
    private String cupdatedby;

    public Mcalakademik() {
    }


    public Mcalakademik(int id, Msekolah msekolah, Mprodi mprodi, String cno) {
        this.id = id;
        this.msekolah = msekolah;
        this.mprodi = mprodi;
        this.cno = cno;
    }

    public Mcalakademik(int id, Mkegiatan mkegiatan, Msekolah msekolah, Mprodi mprodi, String cno, Date dtglawal, Date dtglakhir, String cjamawal, String cjamakhir, String cterm, String cthajar, String csmt, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby) {
        this.id = id;
        this.mkegiatan = mkegiatan;
        this.msekolah = msekolah;
        this.mprodi = mprodi;
        this.cno = cno;
        this.dtglawal = dtglawal;
        this.dtglakhir = dtglakhir;
        this.cjamawal = cjamawal;
        this.cjamakhir = cjamakhir;
        this.cterm = cterm;
        this.cthajar = cthajar;
        this.csmt = csmt;
        this.dcreateddate = dcreateddate;
        this.ccreatedby = ccreatedby;
        this.dupdateddate = dupdateddate;
        this.cupdatedby = cupdatedby;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Msekolah getMsekolah() {
        return this.msekolah;
    }

    public void setMsekolah(Msekolah msekolah) {
        this.msekolah = msekolah;
    }

    public Mprodi getMprodi() {
        return this.mprodi;
    }

    public void setMprodi(Mprodi mprodi) {
        this.mprodi = mprodi;
    }

    public String getCno() {
        return this.cno;
    }

    public void setCno(String cno) {
        this.cno = cno;
    }

    public Date getDtglawal() {
        return this.dtglawal;
    }

    public void setDtglawal(Date dtglawal) {
        this.dtglawal = dtglawal;
    }

    public Date getDtglakhir() {
        return this.dtglakhir;
    }

    public void setDtglakhir(Date dtglakhir) {
        this.dtglakhir = dtglakhir;
    }

    public String getCjamawal() {
        return this.cjamawal;
    }

    public void setCjamawal(String cjamawal) {
        this.cjamawal = cjamawal;
    }

    public String getCjamakhir() {
        return this.cjamakhir;
    }

    public void setCjamakhir(String cjamakhir) {
        this.cjamakhir = cjamakhir;
    }

    public String getCterm() {
        return this.cterm;
    }

    public void setCterm(String cterm) {
        this.cterm = cterm;
    }

    public String getCthajar() {
        return this.cthajar;
    }

    public void setCthajar(String cthajar) {
        this.cthajar = cthajar;
    }

    public String getCsmt() {
        return this.csmt;
    }

    public void setCsmt(String csmt) {
        this.csmt = csmt;
    }

    public Date getDcreateddate() {
        return this.dcreateddate;
    }

    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }

    public String getCcreatedby() {
        return this.ccreatedby;
    }

    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }

    public Date getDupdateddate() {
        return this.dupdateddate;
    }

    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }

    public String getCupdatedby() {
        return this.cupdatedby;
    }

    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }

    public Mkegiatan getMkegiatan() {
        return this.mkegiatan;
    }

    public void setMkegiatan(Mkegiatan mkegiatan) {
        this.mkegiatan = mkegiatan;
    }

}


