package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mhari generated by hbm2java
 */
public class Mhari  implements java.io.Serializable {
	//public static String ID = "id";
    //public static String CODE = "ckdhari";
    //public static String NAME = "cnmhari";

     private int id;
     private String ckdhari;
     private String cnmhari;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdatedate;
     private String dupdatedby;
     private Set<Tabsenmhs> tabsenmhses = new HashSet<Tabsenmhs>(0);
     private Set<Tjadujian> tjadujians = new HashSet<Tjadujian>(0);
     private Set<Tjadkuldetil> tjadkuldetils = new HashSet<Tjadkuldetil>(0);
     private Set<Tabsendosen> tabsendosens = new HashSet<Tabsendosen>(0);

    public Mhari() {
    }

	
    public Mhari(int id, String ckdhari) {
        this.id = id;
        this.ckdhari = ckdhari;
    }
    public Mhari(int id, String ckdhari, String cnmhari, Date dcreateddate, String ccreatedby, Date dupdatedate, String dupdatedby, Set<Tabsenmhs> tabsenmhses, Set<Tjadujian> tjadujians, Set<Tjadkuldetil> tjadkuldetils, Set<Tabsendosen> tabsendosens) {
       this.id = id;
       this.ckdhari = ckdhari;
       this.cnmhari = cnmhari;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdatedate = dupdatedate;
       this.dupdatedby = dupdatedby;
       this.tabsenmhses = tabsenmhses;
       this.tjadujians = tjadujians;
       this.tjadkuldetils = tjadkuldetils;
       this.tabsendosens = tabsendosens;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCkdhari() {
        return this.ckdhari;
    }
    
    public void setCkdhari(String ckdhari) {
        this.ckdhari = ckdhari;
    }
    public String getCnmhari() {
        return this.cnmhari;
    }
    
    public void setCnmhari(String cnmhari) {
        this.cnmhari = cnmhari;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdatedate() {
        return this.dupdatedate;
    }
    
    public void setDupdatedate(Date dupdatedate) {
        this.dupdatedate = dupdatedate;
    }
    public String getDupdatedby() {
        return this.dupdatedby;
    }
    
    public void setDupdatedby(String dupdatedby) {
        this.dupdatedby = dupdatedby;
    }
    public Set<Tabsenmhs> getTabsenmhses() {
        return this.tabsenmhses;
    }
    
    public void setTabsenmhses(Set<Tabsenmhs> tabsenmhses) {
        this.tabsenmhses = tabsenmhses;
    }
    public Set<Tjadujian> getTjadujians() {
        return this.tjadujians;
    }
    
    public void setTjadujians(Set<Tjadujian> tjadujians) {
        this.tjadujians = tjadujians;
    }
    public Set<Tjadkuldetil> getTjadkuldetils() {
        return this.tjadkuldetils;
    }
    
    public void setTjadkuldetils(Set<Tjadkuldetil> tjadkuldetils) {
        this.tjadkuldetils = tjadkuldetils;
    }
    public Set<Tabsendosen> getTabsendosens() {
        return this.tabsendosens;
    }
    
    public void setTabsendosens(Set<Tabsendosen> tabsendosens) {
        this.tabsendosens = tabsendosens;
    }




}


