package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mjenjang generated by hbm2java
 */
public class Mjenjang  implements java.io.Serializable {
	//public static String ID = "id";
    //public static String CODE = "ckdjen";
    //public static String NAME = "cnmjen";
    //public static String SINGKATAN = "csingkat";

     private int id;
     private String ckdjen;
     private String cnmjen;
     private String csingkat;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;
     private Set<Mmahasiswa> mmahasiswas = new HashSet<Mmahasiswa>(0);
     private Set<Mprodi> mprodis = new HashSet<Mprodi>(0);
     private Set<Mhistpnddkmhs> mhistpnddkmhses = new HashSet<Mhistpnddkmhs>(0);
     private Set<Mgrade> mgrades = new HashSet<Mgrade>(0);

    public Mjenjang() {
    }

	
    public Mjenjang(int id, String ckdjen) {
        this.id = id;
        this.ckdjen = ckdjen;
    }
    public Mjenjang(int id, String ckdjen, String cnmjen, String csingkat, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby, Set<Mmahasiswa> mmahasiswas, Set<Mprodi> mprodis, Set<Mhistpnddkmhs> mhistpnddkmhses, Set<Mgrade> mgrades) {
       this.id = id;
       this.ckdjen = ckdjen;
       this.cnmjen = cnmjen;
       this.csingkat = csingkat;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
       this.mmahasiswas = mmahasiswas;
       this.mprodis = mprodis;
       this.mhistpnddkmhses = mhistpnddkmhses;
       this.mgrades = mgrades;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCkdjen() {
        return this.ckdjen;
    }
    
    public void setCkdjen(String ckdjen) {
        this.ckdjen = ckdjen;
    }
    public String getCnmjen() {
        return this.cnmjen;
    }
    
    public void setCnmjen(String cnmjen) {
        this.cnmjen = cnmjen;
    }
    public String getCsingkat() {
        return this.csingkat;
    }
    
    public void setCsingkat(String csingkat) {
        this.csingkat = csingkat;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }
    public Set<Mmahasiswa> getMmahasiswas() {
        return this.mmahasiswas;
    }
    
    public void setMmahasiswas(Set<Mmahasiswa> mmahasiswas) {
        this.mmahasiswas = mmahasiswas;
    }
    public Set<Mprodi> getMprodis() {
        return this.mprodis;
    }
    
    public void setMprodis(Set<Mprodi> mprodis) {
        this.mprodis = mprodis;
    }
    public Set<Mhistpnddkmhs> getMhistpnddkmhses() {
        return this.mhistpnddkmhses;
    }
    
    public void setMhistpnddkmhses(Set<Mhistpnddkmhs> mhistpnddkmhses) {
        this.mhistpnddkmhses = mhistpnddkmhses;
    }
    public Set<Mgrade> getMgrades() {
        return this.mgrades;
    }
    
    public void setMgrades(Set<Mgrade> mgrades) {
        this.mgrades = mgrades;
    }




}


