package id.ac.idu.backend.model;
// Generated 06 Mar 12 10:03:27 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mkegiatan generated by hbm2java
 */
public class Mkegiatan implements java.io.Serializable {


    private int id;
    private String ckdkgt;
    private String cnmkgt;
    private Date dcreateddate;
    private String ccreatedby;
    private Date dupdateddate;
    private String cupdatedby;
    private Set<Mcalakademik> mcalakademiks = new HashSet<Mcalakademik>(0);

    public Mkegiatan() {
    }


    public Mkegiatan(int id, String ckdkgt, String cnmkgt) {
        this.id = id;
        this.ckdkgt = ckdkgt;
        this.cnmkgt = cnmkgt;
    }

    public Mkegiatan(int id, String ckdkgt, String cnmkgt, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby, Set<Mcalakademik> mcalakademiks) {
        this.id = id;
        this.ckdkgt = ckdkgt;
        this.cnmkgt = cnmkgt;
        this.dcreateddate = dcreateddate;
        this.ccreatedby = ccreatedby;
        this.dupdateddate = dupdateddate;
        this.cupdatedby = cupdatedby;
        this.mcalakademiks = mcalakademiks;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCkdkgt() {
        return this.ckdkgt;
    }

    public void setCkdkgt(String ckdkgt) {
        this.ckdkgt = ckdkgt;
    }

    public String getCnmkgt() {
        return this.cnmkgt;
    }

    public void setCnmkgt(String cnmkgt) {
        this.cnmkgt = cnmkgt;
    }

    public Date getDcreateddate() {
        return this.dcreateddate;
    }

    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }

    public String getCcreatedby() {
        return this.ccreatedby;
    }

    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }

    public Date getDupdateddate() {
        return this.dupdateddate;
    }

    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }

    public String getCupdatedby() {
        return this.cupdatedby;
    }

    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }

    public Set<Mcalakademik> getMcalakademiks() {
        return this.mcalakademiks;
    }

    public void setMcalakademiks(Set<Mcalakademik> mcalakademiks) {
        this.mcalakademiks = mcalakademiks;
    }

}


