package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mkel generated by hbm2java
 */
public class Mkel  implements java.io.Serializable {


     private int id;
     private MkodePos mkodePos;
     private String cnamaKel;
     private String kecId;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;
     private Set<Malumni> malumnis = new HashSet<Malumni>(0);

    public Mkel() {
    }

	
    public Mkel(int id, MkodePos mkodePos, String cnamaKel, String kecId) {
        this.id = id;
        this.mkodePos = mkodePos;
        this.cnamaKel = cnamaKel;
        this.kecId = kecId;
    }
    public Mkel(int id, MkodePos mkodePos, String cnamaKel, String kecId, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby, Set<Malumni> malumnis) {
       this.id = id;
       this.mkodePos = mkodePos;
       this.cnamaKel = cnamaKel;
       this.kecId = kecId;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
       this.malumnis = malumnis;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public MkodePos getMkodePos() {
        return this.mkodePos;
    }
    
    public void setMkodePos(MkodePos mkodePos) {
        this.mkodePos = mkodePos;
    }
    public String getCnamaKel() {
        return this.cnamaKel;
    }
    
    public void setCnamaKel(String cnamaKel) {
        this.cnamaKel = cnamaKel;
    }
    public String getKecId() {
        return this.kecId;
    }
    
    public void setKecId(String kecId) {
        this.kecId = kecId;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }
    public Set<Malumni> getMalumnis() {
        return this.malumnis;
    }
    
    public void setMalumnis(Set<Malumni> malumnis) {
        this.malumnis = malumnis;
    }




}


