package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mpegawai generated by hbm2java
 */
public class Mpegawai  implements java.io.Serializable {


     private long id;
     private Mjabatan mjabatan;
     private String cnip;
     private String cnama;
     private String ctmlahir;
     private Date dtglahir;
     private String cjenklmn;
     private String cgldarah;
     private String ckdagama;
     private String cstatus;
     private String cpendakhir;
     private String ckdnegara;
     private String calamatrm;
     private String calamatrm1;
     private Integer ckdposrm;
     private String cproprm;
     private String ctelprma;
     private String ctelprm;
     private String cnohp;
     private String calamattg;
     private String calamattg1;
     private Integer ckdpostg;
     private String cproptg;
     private String cemail;
     private Date ctgmkerja;
     private String cnoskmkerja;
     private Date dtgskmkerja;
     private String cflagaktif;
     private String cgol;
     private String cpnsnip;
     private String cnoktp;
     private String cuser;
     private String cgelardp;
     private String cgelarbk;
     private String cnpwp;
     private String cnomortgmkerja;
     private String cfoto;
     private Date dcreateddate;
     private String createdby;
     private String cupdatedby;
     private Date dupdateddate;
     private Set<Msekolah> msekolahs = new HashSet<Msekolah>(0);
     private Set<Tjadkulmaster> tjadkulmastersForPegawaiId1 = new HashSet<Tjadkulmaster>(0);
     private Set<Tabsendosen> tabsendosens = new HashSet<Tabsendosen>(0);
     private Set<Tjadkulmaster> tjadkulmastersForPegawaiId2 = new HashSet<Tjadkulmaster>(0);

    public Mpegawai() {
    }

	
    public Mpegawai(long id, String cnip, String cflagaktif) {
        this.id = id;
        this.cnip = cnip;
        this.cflagaktif = cflagaktif;
    }
    public Mpegawai(long id, Mjabatan mjabatan, String cnip, String cnama, String ctmlahir, Date dtglahir, String cjenklmn, String cgldarah, String ckdagama, String cstatus, String cpendakhir, String ckdnegara, String calamatrm, String calamatrm1, Integer ckdposrm, String cproprm, String ctelprma, String ctelprm, String cnohp, String calamattg, String calamattg1, Integer ckdpostg, String cproptg, String cemail, Date ctgmkerja, String cnoskmkerja, Date dtgskmkerja, String cflagaktif, String cgol, String cpnsnip, String cnoktp, String cuser, String cgelardp, String cgelarbk, String cnpwp, String cnomortgmkerja, String cfoto, Date dcreateddate, String createdby, String cupdatedby, Date dupdateddate, Set<Msekolah> msekolahs, Set<Tjadkulmaster> tjadkulmastersForPegawaiId1, Set<Tabsendosen> tabsendosens, Set<Tjadkulmaster> tjadkulmastersForPegawaiId2) {
       this.id = id;
       this.mjabatan = mjabatan;
       this.cnip = cnip;
       this.cnama = cnama;
       this.ctmlahir = ctmlahir;
       this.dtglahir = dtglahir;
       this.cjenklmn = cjenklmn;
       this.cgldarah = cgldarah;
       this.ckdagama = ckdagama;
       this.cstatus = cstatus;
       this.cpendakhir = cpendakhir;
       this.ckdnegara = ckdnegara;
       this.calamatrm = calamatrm;
       this.calamatrm1 = calamatrm1;
       this.ckdposrm = ckdposrm;
       this.cproprm = cproprm;
       this.ctelprma = ctelprma;
       this.ctelprm = ctelprm;
       this.cnohp = cnohp;
       this.calamattg = calamattg;
       this.calamattg1 = calamattg1;
       this.ckdpostg = ckdpostg;
       this.cproptg = cproptg;
       this.cemail = cemail;
       this.ctgmkerja = ctgmkerja;
       this.cnoskmkerja = cnoskmkerja;
       this.dtgskmkerja = dtgskmkerja;
       this.cflagaktif = cflagaktif;
       this.cgol = cgol;
       this.cpnsnip = cpnsnip;
       this.cnoktp = cnoktp;
       this.cuser = cuser;
       this.cgelardp = cgelardp;
       this.cgelarbk = cgelarbk;
       this.cnpwp = cnpwp;
       this.cnomortgmkerja = cnomortgmkerja;
       this.cfoto = cfoto;
       this.dcreateddate = dcreateddate;
       this.createdby = createdby;
       this.cupdatedby = cupdatedby;
       this.dupdateddate = dupdateddate;
       this.msekolahs = msekolahs;
       this.tjadkulmastersForPegawaiId1 = tjadkulmastersForPegawaiId1;
       this.tabsendosens = tabsendosens;
       this.tjadkulmastersForPegawaiId2 = tjadkulmastersForPegawaiId2;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Mjabatan getMjabatan() {
        return this.mjabatan;
    }
    
    public void setMjabatan(Mjabatan mjabatan) {
        this.mjabatan = mjabatan;
    }
    public String getCnip() {
        return this.cnip;
    }
    
    public void setCnip(String cnip) {
        this.cnip = cnip;
    }
    public String getCnama() {
        return this.cnama;
    }
    
    public void setCnama(String cnama) {
        this.cnama = cnama;
    }
    public String getCtmlahir() {
        return this.ctmlahir;
    }
    
    public void setCtmlahir(String ctmlahir) {
        this.ctmlahir = ctmlahir;
    }
    public Date getDtglahir() {
        return this.dtglahir;
    }
    
    public void setDtglahir(Date dtglahir) {
        this.dtglahir = dtglahir;
    }
    public String getCjenklmn() {
        return this.cjenklmn;
    }
    
    public void setCjenklmn(String cjenklmn) {
        this.cjenklmn = cjenklmn;
    }
    public String getCgldarah() {
        return this.cgldarah;
    }
    
    public void setCgldarah(String cgldarah) {
        this.cgldarah = cgldarah;
    }
    public String getCkdagama() {
        return this.ckdagama;
    }
    
    public void setCkdagama(String ckdagama) {
        this.ckdagama = ckdagama;
    }
    public String getCstatus() {
        return this.cstatus;
    }
    
    public void setCstatus(String cstatus) {
        this.cstatus = cstatus;
    }
    public String getCpendakhir() {
        return this.cpendakhir;
    }
    
    public void setCpendakhir(String cpendakhir) {
        this.cpendakhir = cpendakhir;
    }
    public String getCkdnegara() {
        return this.ckdnegara;
    }
    
    public void setCkdnegara(String ckdnegara) {
        this.ckdnegara = ckdnegara;
    }
    public String getCalamatrm() {
        return this.calamatrm;
    }
    
    public void setCalamatrm(String calamatrm) {
        this.calamatrm = calamatrm;
    }
    public String getCalamatrm1() {
        return this.calamatrm1;
    }
    
    public void setCalamatrm1(String calamatrm1) {
        this.calamatrm1 = calamatrm1;
    }
    public Integer getCkdposrm() {
        return this.ckdposrm;
    }
    
    public void setCkdposrm(Integer ckdposrm) {
        this.ckdposrm = ckdposrm;
    }
    public String getCproprm() {
        return this.cproprm;
    }
    
    public void setCproprm(String cproprm) {
        this.cproprm = cproprm;
    }
    public String getCtelprma() {
        return this.ctelprma;
    }
    
    public void setCtelprma(String ctelprma) {
        this.ctelprma = ctelprma;
    }
    public String getCtelprm() {
        return this.ctelprm;
    }
    
    public void setCtelprm(String ctelprm) {
        this.ctelprm = ctelprm;
    }
    public String getCnohp() {
        return this.cnohp;
    }
    
    public void setCnohp(String cnohp) {
        this.cnohp = cnohp;
    }
    public String getCalamattg() {
        return this.calamattg;
    }
    
    public void setCalamattg(String calamattg) {
        this.calamattg = calamattg;
    }
    public String getCalamattg1() {
        return this.calamattg1;
    }
    
    public void setCalamattg1(String calamattg1) {
        this.calamattg1 = calamattg1;
    }
    public Integer getCkdpostg() {
        return this.ckdpostg;
    }
    
    public void setCkdpostg(Integer ckdpostg) {
        this.ckdpostg = ckdpostg;
    }
    public String getCproptg() {
        return this.cproptg;
    }
    
    public void setCproptg(String cproptg) {
        this.cproptg = cproptg;
    }
    public String getCemail() {
        return this.cemail;
    }
    
    public void setCemail(String cemail) {
        this.cemail = cemail;
    }
    public Date getCtgmkerja() {
        return this.ctgmkerja;
    }
    
    public void setCtgmkerja(Date ctgmkerja) {
        this.ctgmkerja = ctgmkerja;
    }
    public String getCnoskmkerja() {
        return this.cnoskmkerja;
    }
    
    public void setCnoskmkerja(String cnoskmkerja) {
        this.cnoskmkerja = cnoskmkerja;
    }
    public Date getDtgskmkerja() {
        return this.dtgskmkerja;
    }
    
    public void setDtgskmkerja(Date dtgskmkerja) {
        this.dtgskmkerja = dtgskmkerja;
    }
    public String getCflagaktif() {
        return this.cflagaktif;
    }
    
    public void setCflagaktif(String cflagaktif) {
        this.cflagaktif = cflagaktif;
    }
    public String getCgol() {
        return this.cgol;
    }
    
    public void setCgol(String cgol) {
        this.cgol = cgol;
    }
    public String getCpnsnip() {
        return this.cpnsnip;
    }
    
    public void setCpnsnip(String cpnsnip) {
        this.cpnsnip = cpnsnip;
    }
    public String getCnoktp() {
        return this.cnoktp;
    }
    
    public void setCnoktp(String cnoktp) {
        this.cnoktp = cnoktp;
    }
    public String getCuser() {
        return this.cuser;
    }
    
    public void setCuser(String cuser) {
        this.cuser = cuser;
    }
    public String getCgelardp() {
        return this.cgelardp;
    }
    
    public void setCgelardp(String cgelardp) {
        this.cgelardp = cgelardp;
    }
    public String getCgelarbk() {
        return this.cgelarbk;
    }
    
    public void setCgelarbk(String cgelarbk) {
        this.cgelarbk = cgelarbk;
    }
    public String getCnpwp() {
        return this.cnpwp;
    }
    
    public void setCnpwp(String cnpwp) {
        this.cnpwp = cnpwp;
    }
    public String getCnomortgmkerja() {
        return this.cnomortgmkerja;
    }
    
    public void setCnomortgmkerja(String cnomortgmkerja) {
        this.cnomortgmkerja = cnomortgmkerja;
    }
    public String getCfoto() {
        return this.cfoto;
    }
    
    public void setCfoto(String cfoto) {
        this.cfoto = cfoto;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public Set<Msekolah> getMsekolahs() {
        return this.msekolahs;
    }
    
    public void setMsekolahs(Set<Msekolah> msekolahs) {
        this.msekolahs = msekolahs;
    }
    public Set<Tjadkulmaster> getTjadkulmastersForPegawaiId1() {
        return this.tjadkulmastersForPegawaiId1;
    }
    
    public void setTjadkulmastersForPegawaiId1(Set<Tjadkulmaster> tjadkulmastersForPegawaiId1) {
        this.tjadkulmastersForPegawaiId1 = tjadkulmastersForPegawaiId1;
    }
    public Set<Tabsendosen> getTabsendosens() {
        return this.tabsendosens;
    }
    
    public void setTabsendosens(Set<Tabsendosen> tabsendosens) {
        this.tabsendosens = tabsendosens;
    }
    public Set<Tjadkulmaster> getTjadkulmastersForPegawaiId2() {
        return this.tjadkulmastersForPegawaiId2;
    }
    
    public void setTjadkulmastersForPegawaiId2(Set<Tjadkulmaster> tjadkulmastersForPegawaiId2) {
        this.tjadkulmastersForPegawaiId2 = tjadkulmastersForPegawaiId2;
    }




}


