package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mruang generated by hbm2java
 */
public class Mruang  implements java.io.Serializable {


     private int id;
     private String ckdruang;
     private String cnmRuang;
     private int nmaxIsi;
     private int nmaxUji;
     private char cstatus;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;
     private Set<Mfasilitasruang> mfasilitasruangs = new HashSet<Mfasilitasruang>(0);
     private Set<Tirspasca> tirspascas = new HashSet<Tirspasca>(0);
     private Set<Tabsendosen> tabsendosens = new HashSet<Tabsendosen>(0);
     private Set<Tjadujian> tjadujians = new HashSet<Tjadujian>(0);
     private Set<Tjadkuldetil> tjadkuldetils = new HashSet<Tjadkuldetil>(0);

    public Mruang() {
    }

	
    public Mruang(int id, String ckdruang, String cnmRuang, int nmaxIsi, int nmaxUji, char cstatus) {
        this.id = id;
        this.ckdruang = ckdruang;
        this.cnmRuang = cnmRuang;
        this.nmaxIsi = nmaxIsi;
        this.nmaxUji = nmaxUji;
        this.cstatus = cstatus;
    }
    public Mruang(int id, String ckdruang, String cnmRuang, int nmaxIsi, int nmaxUji, char cstatus, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby, Set<Mfasilitasruang> mfasilitasruangs, Set<Tirspasca> tirspascas, Set<Tabsendosen> tabsendosens, Set<Tjadujian> tjadujians, Set<Tjadkuldetil> tjadkuldetils) {
       this.id = id;
       this.ckdruang = ckdruang;
       this.cnmRuang = cnmRuang;
       this.nmaxIsi = nmaxIsi;
       this.nmaxUji = nmaxUji;
       this.cstatus = cstatus;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
       this.mfasilitasruangs = mfasilitasruangs;
       this.tirspascas = tirspascas;
       this.tabsendosens = tabsendosens;
       this.tjadujians = tjadujians;
       this.tjadkuldetils = tjadkuldetils;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCkdruang() {
        return this.ckdruang;
    }
    
    public void setCkdruang(String ckdruang) {
        this.ckdruang = ckdruang;
    }
    public String getCnmRuang() {
        return this.cnmRuang;
    }
    
    public void setCnmRuang(String cnmRuang) {
        this.cnmRuang = cnmRuang;
    }
    public int getNmaxIsi() {
        return this.nmaxIsi;
    }
    
    public void setNmaxIsi(int nmaxIsi) {
        this.nmaxIsi = nmaxIsi;
    }
    public int getNmaxUji() {
        return this.nmaxUji;
    }
    
    public void setNmaxUji(int nmaxUji) {
        this.nmaxUji = nmaxUji;
    }
    public char getCstatus() {
        return this.cstatus;
    }
    
    public void setCstatus(char cstatus) {
        this.cstatus = cstatus;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }
    public Set<Mfasilitasruang> getMfasilitasruangs() {
        return this.mfasilitasruangs;
    }
    
    public void setMfasilitasruangs(Set<Mfasilitasruang> mfasilitasruangs) {
        this.mfasilitasruangs = mfasilitasruangs;
    }
    public Set<Tirspasca> getTirspascas() {
        return this.tirspascas;
    }
    
    public void setTirspascas(Set<Tirspasca> tirspascas) {
        this.tirspascas = tirspascas;
    }
    public Set<Tabsendosen> getTabsendosens() {
        return this.tabsendosens;
    }
    
    public void setTabsendosens(Set<Tabsendosen> tabsendosens) {
        this.tabsendosens = tabsendosens;
    }
    public Set<Tjadujian> getTjadujians() {
        return this.tjadujians;
    }
    
    public void setTjadujians(Set<Tjadujian> tjadujians) {
        this.tjadujians = tjadujians;
    }
    public Set<Tjadkuldetil> getTjadkuldetils() {
        return this.tjadkuldetils;
    }
    
    public void setTjadkuldetils(Set<Tjadkuldetil> tjadkuldetils) {
        this.tjadkuldetils = tjadkuldetils;
    }




}


