package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tcutimhs generated by hbm2java
 */
public class Tcutimhs  implements java.io.Serializable {


     private String cnosurat;
     private Mmahasiswa mmahasiswa;
     private Date dtglsurat;
     private String cterm;
     private String cthajar;
     private String cket;
     private String cjenis;
     private Date dcreateddate;
     private String createdby;
     private Date dupdateddate;
     private String cupdatedby;

    public Tcutimhs() {
    }

	
    public Tcutimhs(String cnosurat) {
        this.cnosurat = cnosurat;
    }
    public Tcutimhs(String cnosurat, Mmahasiswa mmahasiswa, Date dtglsurat, String cterm, String cthajar, String cket, String cjenis, Date dcreateddate, String createdby, Date dupdateddate, String cupdatedby) {
       this.cnosurat = cnosurat;
       this.mmahasiswa = mmahasiswa;
       this.dtglsurat = dtglsurat;
       this.cterm = cterm;
       this.cthajar = cthajar;
       this.cket = cket;
       this.cjenis = cjenis;
       this.dcreateddate = dcreateddate;
       this.createdby = createdby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
    }
   
    public String getCnosurat() {
        return this.cnosurat;
    }
    
    public void setCnosurat(String cnosurat) {
        this.cnosurat = cnosurat;
    }
    public Mmahasiswa getMmahasiswa() {
        return this.mmahasiswa;
    }
    
    public void setMmahasiswa(Mmahasiswa mmahasiswa) {
        this.mmahasiswa = mmahasiswa;
    }
    public Date getDtglsurat() {
        return this.dtglsurat;
    }
    
    public void setDtglsurat(Date dtglsurat) {
        this.dtglsurat = dtglsurat;
    }
    public String getCterm() {
        return this.cterm;
    }
    
    public void setCterm(String cterm) {
        this.cterm = cterm;
    }
    public String getCthajar() {
        return this.cthajar;
    }
    
    public void setCthajar(String cthajar) {
        this.cthajar = cthajar;
    }
    public String getCket() {
        return this.cket;
    }
    
    public void setCket(String cket) {
        this.cket = cket;
    }
    public String getCjenis() {
        return this.cjenis;
    }
    
    public void setCjenis(String cjenis) {
        this.cjenis = cjenis;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }




}


