package id.ac.idu.backend.model;// default package
// Generated Mar 21, 2012 2:09:06 AM by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * Tfeedbackalumni generated by hbm2java
 */

public class Tfeedbackalumni  implements java.io.Serializable {


    // Fields    

     private int id;
     private Mfeedback mfeedback;
     private String cterm;
     private Msekolah msekolah;
     private Mprodi mprodi;
     private String ckelompok;
     private Mmahasiswa mmahasiswa;
     private int nnopertanyaan;
     private String cjawaban;
     private String ccreatedby;
     private Date dcreateddate;
     private String cupdateby;
     private Date dupdateddate;


    // Constructors

    /** default constructor */
    public Tfeedbackalumni() {
    }

	/** minimal constructor */
    public Tfeedbackalumni(int id, String cterm, Msekolah msekolah, Mprodi mprodi, String ckelompok, Mmahasiswa mmahasiswa, Mfeedback mfeedback, int nnopertanyaan) {
        this.id = id;
        this.mfeedback = mfeedback;
        this.cterm = cterm;
        this.msekolah = msekolah;
        this.mprodi = mprodi;
        this.ckelompok = ckelompok;
        this.mmahasiswa = mmahasiswa;
        this.nnopertanyaan = nnopertanyaan;
    }
    
    /** full constructor */
    public Tfeedbackalumni(int id, String cterm, Msekolah msekolah, Mprodi mprodi, String ckelompok, Mmahasiswa mmahasiswa, Mfeedback mfeedback, int nnopertanyaan, String cjawaban, String ccreatedby, Date dcreateddate, String cupdateby, Date dupdateddate) {
        this.id = id;
        this.mfeedback = mfeedback;
        this.cterm = cterm;
        this.msekolah = msekolah;
        this.mprodi = mprodi;
        this.ckelompok = ckelompok;
        this.mmahasiswa = mmahasiswa;
        this.nnopertanyaan = nnopertanyaan;
        this.cjawaban = cjawaban;
        this.ccreatedby = ccreatedby;
        this.dcreateddate = dcreateddate;
        this.cupdateby = cupdateby;
        this.dupdateddate = dupdateddate;
    }
    

   
    // Property accessors

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    public Mfeedback getMfeedback() {
        return this.mfeedback;
    }
    
    public void setMfeedback(Mfeedback mfeedback) {
        this.mfeedback = mfeedback;
    }

    public String getCterm() {
        return this.cterm;
    }
    
    public void setCterm(String cterm) {
        this.cterm = cterm;
    }

    public Msekolah getMsekolah() {
        return this.msekolah;
    }
    
    public void setMsekolah(Msekolah msekolah) {
        this.msekolah = msekolah;
    }

    public Mprodi getMprodi() {
        return this.mprodi;
    }
    
    public void setMprodi(Mprodi mprodi) {
        this.mprodi = mprodi;
    }

    public String getCkelompok() {
        return this.ckelompok;
    }
    
    public void setCkelompok(String ckelompok) {
        this.ckelompok = ckelompok;
    }

    public Mmahasiswa getMmahasiswa() {
        return this.mmahasiswa;
    }
    
    public void setMmahasiswa(Mmahasiswa mmahasiswa) {
        this.mmahasiswa = mmahasiswa;
    }

    public int getNnopertanyaan() {
        return this.nnopertanyaan;
    }
    
    public void setNnopertanyaan(int nnopertanyaan) {
        this.nnopertanyaan = nnopertanyaan;
    }

    public String getCjawaban() {
        return this.cjawaban;
    }
    
    public void setCjawaban(String cjawaban) {
        this.cjawaban = cjawaban;
    }

    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }

    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }

    public String getCupdateby() {
        return this.cupdateby;
    }
    
    public void setCupdateby(String cupdateby) {
        this.cupdateby = cupdateby;
    }

    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
   








}
