package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Thistkerja generated by hbm2java
 */
public class Thistkerja  implements java.io.Serializable {


     private int id;
     private Mbidangusaha mbidangusaha;
     private Msekolah msekolah;
     private Mprodi mprodi;
     private String cterm;
     private String cnim;
     private int nnourut;
     private char cjnsinstansi;
     private String cnminstansi;
     private String calinstansi;
     private String ckdkerja;
     private String ckdgaji;
     private String ccreatedby;
     private Date ccreateddate;
     private String cupdatedby;
     private Date cupdateddate;

    public Thistkerja() {
    }

	
    public Thistkerja(int id, Mbidangusaha mbidangusaha, Msekolah msekolah, Mprodi mprodi, String cterm, String cnim, int nnourut, char cjnsinstansi, String cnminstansi, String calinstansi) {
        this.id = id;
        this.mbidangusaha = mbidangusaha;
        this.msekolah = msekolah;
        this.mprodi = mprodi;
        this.cterm = cterm;
        this.cnim = cnim;
        this.nnourut = nnourut;
        this.cjnsinstansi = cjnsinstansi;
        this.cnminstansi = cnminstansi;
        this.calinstansi = calinstansi;
    }
    public Thistkerja(int id, Mbidangusaha mbidangusaha, Msekolah msekolah, Mprodi mprodi, String cterm, String cnim, int nnourut, char cjnsinstansi, String cnminstansi, String calinstansi, String ckdkerja, String ckdgaji, String ccreatedby, Date ccreateddate, String cupdatedby, Date cupdateddate) {
       this.id = id;
       this.mbidangusaha = mbidangusaha;
       this.msekolah = msekolah;
       this.mprodi = mprodi;
       this.cterm = cterm;
       this.cnim = cnim;
       this.nnourut = nnourut;
       this.cjnsinstansi = cjnsinstansi;
       this.cnminstansi = cnminstansi;
       this.calinstansi = calinstansi;
       this.ckdkerja = ckdkerja;
       this.ckdgaji = ckdgaji;
       this.ccreatedby = ccreatedby;
       this.ccreateddate = ccreateddate;
       this.cupdatedby = cupdatedby;
       this.cupdateddate = cupdateddate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mbidangusaha getMbidangusaha() {
        return this.mbidangusaha;
    }
    
    public void setMbidangusaha(Mbidangusaha mbidangusaha) {
        this.mbidangusaha = mbidangusaha;
    }
    public Msekolah getMsekolah() {
        return this.msekolah;
    }
    
    public void setMsekolah(Msekolah msekolah) {
        this.msekolah = msekolah;
    }
    public Mprodi getMprodi() {
        return this.mprodi;
    }
    
    public void setMprodi(Mprodi mprodi) {
        this.mprodi = mprodi;
    }
    public String getCterm() {
        return this.cterm;
    }
    
    public void setCterm(String cterm) {
        this.cterm = cterm;
    }
    public String getCnim() {
        return this.cnim;
    }
    
    public void setCnim(String cnim) {
        this.cnim = cnim;
    }
    public int getNnourut() {
        return this.nnourut;
    }
    
    public void setNnourut(int nnourut) {
        this.nnourut = nnourut;
    }
    public char getCjnsinstansi() {
        return this.cjnsinstansi;
    }
    
    public void setCjnsinstansi(char cjnsinstansi) {
        this.cjnsinstansi = cjnsinstansi;
    }
    public String getCnminstansi() {
        return this.cnminstansi;
    }
    
    public void setCnminstansi(String cnminstansi) {
        this.cnminstansi = cnminstansi;
    }
    public String getCalinstansi() {
        return this.calinstansi;
    }
    
    public void setCalinstansi(String calinstansi) {
        this.calinstansi = calinstansi;
    }
    public String getCkdkerja() {
        return this.ckdkerja;
    }
    
    public void setCkdkerja(String ckdkerja) {
        this.ckdkerja = ckdkerja;
    }
    public String getCkdgaji() {
        return this.ckdgaji;
    }
    
    public void setCkdgaji(String ckdgaji) {
        this.ckdgaji = ckdgaji;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getCcreateddate() {
        return this.ccreateddate;
    }
    
    public void setCcreateddate(Date ccreateddate) {
        this.ccreateddate = ccreateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }
    public Date getCupdateddate() {
        return this.cupdateddate;
    }
    
    public void setCupdateddate(Date cupdateddate) {
        this.cupdateddate = cupdateddate;
    }




}


