package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tirspasca generated by hbm2java
 */
public class Tirspasca  implements java.io.Serializable {
    /*public static String RUANG = "mruang";
    public static String SEKOLAH = "msekolah";
    public static String PRODI = "mprodi";
    public static String MAHASISWA = "mmahasiswa";
    public static String MATAKULIAH = "mtbmtkl";
    public static String GRADE = "mgrade";
    public static String TERM = "cterm";
    public static String KELOMPOK = "ckelompok";*/


     private int id;
     private Mruang mruang;
     private Msekolah msekolah;
     private Mprodi mprodi;
     private Mmahasiswa mmahasiswa;
     private Mtbmtkl mtbmtkl;
     private Mgrade mgrade;
     private String cterm;
     private String ckelompok;
     private Integer nsks;
     private Integer nnilabs;
     private Integer nniltgs;
     private Integer nniluts;
     private Integer nniluas;
     private Integer nnilakh;
     private String cflagver;
     private String cflaggab;
     private String cthajar;
     private String csmt;
     private Integer nhadir;
     private Integer nizin;
     private Integer nsakit;
     private Integer nalpa;
     private Date dcreateddate;
     private String ccreatedby;
     private Date dupdateddate;
     private String cupdatedby;

    public Tirspasca() {
    }

	
    public Tirspasca(int id, Msekolah msekolah, Mprodi mprodi, Mmahasiswa mmahasiswa, Mtbmtkl mtbmtkl, String cterm, String ckelompok) {
        this.id = id;
        this.msekolah = msekolah;
        this.mprodi = mprodi;
        this.mmahasiswa = mmahasiswa;
        this.mtbmtkl = mtbmtkl;
        this.cterm = cterm;
        this.ckelompok = ckelompok;
    }
    public Tirspasca(int id, Mruang mruang, Msekolah msekolah, Mprodi mprodi, Mmahasiswa mmahasiswa, Mtbmtkl mtbmtkl, Mgrade mgrade, String cterm, String ckelompok, Integer nsks, Integer nnilabs, Integer nniltgs, Integer nniluts, Integer nniluas, Integer nnilakh, String cflagver, String cflaggab, String cthajar, String csmt, Integer nhadir, Integer nizin, Integer nsakit, Integer nalpa, Date dcreateddate, String ccreatedby, Date dupdateddate, String cupdatedby) {
       this.id = id;
       this.mruang = mruang;
       this.msekolah = msekolah;
       this.mprodi = mprodi;
       this.mmahasiswa = mmahasiswa;
       this.mtbmtkl = mtbmtkl;
       this.mgrade = mgrade;
       this.cterm = cterm;
       this.ckelompok = ckelompok;
       this.nsks = nsks;
       this.nnilabs = nnilabs;
       this.nniltgs = nniltgs;
       this.nniluts = nniluts;
       this.nniluas = nniluas;
       this.nnilakh = nnilakh;
       this.cflagver = cflagver;
       this.cflaggab = cflaggab;
       this.cthajar = cthajar;
       this.csmt = csmt;
       this.nhadir = nhadir;
       this.nizin = nizin;
       this.nsakit = nsakit;
       this.nalpa = nalpa;
       this.dcreateddate = dcreateddate;
       this.ccreatedby = ccreatedby;
       this.dupdateddate = dupdateddate;
       this.cupdatedby = cupdatedby;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mruang getMruang() {
        return this.mruang;
    }
    
    public void setMruang(Mruang mruang) {
        this.mruang = mruang;
    }
    public Msekolah getMsekolah() {
        return this.msekolah;
    }
    
    public void setMsekolah(Msekolah msekolah) {
        this.msekolah = msekolah;
    }
    public Mprodi getMprodi() {
        return this.mprodi;
    }
    
    public void setMprodi(Mprodi mprodi) {
        this.mprodi = mprodi;
    }
    public Mmahasiswa getMmahasiswa() {
        return this.mmahasiswa;
    }
    
    public void setMmahasiswa(Mmahasiswa mmahasiswa) {
        this.mmahasiswa = mmahasiswa;
    }
    public Mtbmtkl getMtbmtkl() {
        return this.mtbmtkl;
    }
    
    public void setMtbmtkl(Mtbmtkl mtbmtkl) {
        this.mtbmtkl = mtbmtkl;
    }
    public Mgrade getMgrade() {
        return this.mgrade;
    }
    
    public void setMgrade(Mgrade mgrade) {
        this.mgrade = mgrade;
    }
    public String getCterm() {
        return this.cterm;
    }
    
    public void setCterm(String cterm) {
        this.cterm = cterm;
    }
    public String getCkelompok() {
        return this.ckelompok;
    }
    
    public void setCkelompok(String ckelompok) {
        this.ckelompok = ckelompok;
    }
    public Integer getNsks() {
        return this.nsks;
    }
    
    public void setNsks(Integer nsks) {
        this.nsks = nsks;
    }
    public Integer getNnilabs() {
        return this.nnilabs;
    }
    
    public void setNnilabs(Integer nnilabs) {
        this.nnilabs = nnilabs;
    }
    public Integer getNniltgs() {
        return this.nniltgs;
    }
    
    public void setNniltgs(Integer nniltgs) {
        this.nniltgs = nniltgs;
    }
    public Integer getNniluts() {
        return this.nniluts;
    }
    
    public void setNniluts(Integer nniluts) {
        this.nniluts = nniluts;
    }
    public Integer getNniluas() {
        return this.nniluas;
    }
    
    public void setNniluas(Integer nniluas) {
        this.nniluas = nniluas;
    }
    public Integer getNnilakh() {
        return this.nnilakh;
    }
    
    public void setNnilakh(Integer nnilakh) {
        this.nnilakh = nnilakh;
    }
    public String getCflagver() {
        return this.cflagver;
    }
    
    public void setCflagver(String cflagver) {
        this.cflagver = cflagver;
    }
    public String getCflaggab() {
        return this.cflaggab;
    }
    
    public void setCflaggab(String cflaggab) {
        this.cflaggab = cflaggab;
    }
    public String getCthajar() {
        return this.cthajar;
    }
    
    public void setCthajar(String cthajar) {
        this.cthajar = cthajar;
    }
    public String getCsmt() {
        return this.csmt;
    }
    
    public void setCsmt(String csmt) {
        this.csmt = csmt;
    }
    public Integer getNhadir() {
        return this.nhadir;
    }
    
    public void setNhadir(Integer nhadir) {
        this.nhadir = nhadir;
    }
    public Integer getNizin() {
        return this.nizin;
    }
    
    public void setNizin(Integer nizin) {
        this.nizin = nizin;
    }
    public Integer getNsakit() {
        return this.nsakit;
    }
    
    public void setNsakit(Integer nsakit) {
        this.nsakit = nsakit;
    }
    public Integer getNalpa() {
        return this.nalpa;
    }
    
    public void setNalpa(Integer nalpa) {
        this.nalpa = nalpa;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }




}


