package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Tjadsidangtugasmenulis generated by hbm2java
 */
public class Tjadsidangtugasmenulis  implements java.io.Serializable {


     private int nrecid;
     private String ckdsekolah;
     private String ckdprogst;
     private String cterm;
     private String cthajar;
     private String csmt;
     private String cnim;
     private String ckdruang;
     private String cjenismenulis;
     private String cjenispenguji;
     private Date dtglsidang;
     private String ckdsesi;
     private String cnip;
     private BigDecimal nnilai;
     private String ccreatedby;
     private Date dcreateddate;
     private String cupdatedby;
     private Date dupdateddate;

    public Tjadsidangtugasmenulis() {
    }

	
    public Tjadsidangtugasmenulis(int nrecid, String ckdsekolah, String ckdprogst, String cterm, String cnim, String cnip) {
        this.nrecid = nrecid;
        this.ckdsekolah = ckdsekolah;
        this.ckdprogst = ckdprogst;
        this.cterm = cterm;
        this.cnim = cnim;
        this.cnip = cnip;
    }
    public Tjadsidangtugasmenulis(int nrecid, String ckdsekolah, String ckdprogst, String cterm, String cthajar, String csmt, String cnim, String ckdruang, String cjenismenulis, String cjenispenguji, Date dtglsidang, String ckdsesi, String cnip, BigDecimal nnilai, String ccreatedby, Date dcreateddate, String cupdatedby, Date dupdateddate) {
       this.nrecid = nrecid;
       this.ckdsekolah = ckdsekolah;
       this.ckdprogst = ckdprogst;
       this.cterm = cterm;
       this.cthajar = cthajar;
       this.csmt = csmt;
       this.cnim = cnim;
       this.ckdruang = ckdruang;
       this.cjenismenulis = cjenismenulis;
       this.cjenispenguji = cjenispenguji;
       this.dtglsidang = dtglsidang;
       this.ckdsesi = ckdsesi;
       this.cnip = cnip;
       this.nnilai = nnilai;
       this.ccreatedby = ccreatedby;
       this.dcreateddate = dcreateddate;
       this.cupdatedby = cupdatedby;
       this.dupdateddate = dupdateddate;
    }
   
    public int getNrecid() {
        return this.nrecid;
    }
    
    public void setNrecid(int nrecid) {
        this.nrecid = nrecid;
    }
    public String getCkdsekolah() {
        return this.ckdsekolah;
    }
    
    public void setCkdsekolah(String ckdsekolah) {
        this.ckdsekolah = ckdsekolah;
    }
    public String getCkdprogst() {
        return this.ckdprogst;
    }
    
    public void setCkdprogst(String ckdprogst) {
        this.ckdprogst = ckdprogst;
    }
    public String getCterm() {
        return this.cterm;
    }
    
    public void setCterm(String cterm) {
        this.cterm = cterm;
    }
    public String getCthajar() {
        return this.cthajar;
    }
    
    public void setCthajar(String cthajar) {
        this.cthajar = cthajar;
    }
    public String getCsmt() {
        return this.csmt;
    }
    
    public void setCsmt(String csmt) {
        this.csmt = csmt;
    }
    public String getCnim() {
        return this.cnim;
    }
    
    public void setCnim(String cnim) {
        this.cnim = cnim;
    }
    public String getCkdruang() {
        return this.ckdruang;
    }
    
    public void setCkdruang(String ckdruang) {
        this.ckdruang = ckdruang;
    }
    public String getCjenismenulis() {
        return this.cjenismenulis;
    }
    
    public void setCjenismenulis(String cjenismenulis) {
        this.cjenismenulis = cjenismenulis;
    }
    public String getCjenispenguji() {
        return this.cjenispenguji;
    }
    
    public void setCjenispenguji(String cjenispenguji) {
        this.cjenispenguji = cjenispenguji;
    }
    public Date getDtglsidang() {
        return this.dtglsidang;
    }
    
    public void setDtglsidang(Date dtglsidang) {
        this.dtglsidang = dtglsidang;
    }
    public String getCkdsesi() {
        return this.ckdsesi;
    }
    
    public void setCkdsesi(String ckdsesi) {
        this.ckdsesi = ckdsesi;
    }
    public String getCnip() {
        return this.cnip;
    }
    
    public void setCnip(String cnip) {
        this.cnip = cnip;
    }
    public BigDecimal getNnilai() {
        return this.nnilai;
    }
    
    public void setNnilai(BigDecimal nnilai) {
        this.nnilai = nnilai;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }




}


