package id.ac.idu.backend.model;
// Generated 10 Mar 12 12:50:36 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tjadkuldetil generated by hbm2java
 */
public class Tjadkuldetil implements java.io.Serializable {

    private int id = Integer.MIN_VALUE;
    private String cterm;
    private Msekolah msekolah;
    private Mprodi mprodi;
    private Mtbmtkl mtbmtkl;
    private String ckelompok;
    private Mhari mhari;
    private Msesikuliah msesikuliah;
    private Mruang mruang;
    private Tjadkulmaster tjadkulmaster;
    private String clintasprodi;
    private Integer njmlsesi;
    private Integer nmaks;
    private Integer nisi;
    private Date dcreateddate;
    private String ccreatedby;
    private Date dupdateddate;
    private String cupdatedby;

    public Tjadkuldetil() {
    }

    public boolean isNew() {
        return (getId() == Integer.MIN_VALUE);
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Mhari getMhari() {
        return mhari;
    }

    public void setMhari(Mhari mhari) {
        this.mhari = mhari;
    }

    public Msesikuliah getMsesikuliah() {
        return msesikuliah;
    }

    public void setMsesikuliah(Msesikuliah msesikuliah) {
        this.msesikuliah = msesikuliah;
    }

    public Mruang getMruang() {
        return mruang;
    }

    public void setMruang(Mruang mruang) {
        this.mruang = mruang;
    }

    public Tjadkulmaster getTjadkulmaster() {
        return tjadkulmaster;
    }

    public void setTjadkulmaster(Tjadkulmaster tjadkulmaster) {
        this.tjadkulmaster = tjadkulmaster;
    }

    public String getClintasprodi() {
        return this.clintasprodi;
    }

    public void setClintasprodi(String clintasprodi) {
        this.clintasprodi = clintasprodi;
    }

    public Integer getNjmlsesi() {
        return this.njmlsesi;
    }

    public void setNjmlsesi(Integer njmlsesi) {
        this.njmlsesi = njmlsesi;
    }

    public Integer getNmaks() {
        return this.nmaks;
    }

    public void setNmaks(Integer nmaks) {
        this.nmaks = nmaks;
    }

    public Integer getNisi() {
        return this.nisi;
    }

    public void setNisi(Integer nisi) {
        this.nisi = nisi;
    }

    public Date getDcreateddate() {
        return this.dcreateddate;
    }

    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }

    public String getCcreatedby() {
        return this.ccreatedby;
    }

    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }

    public Date getDupdateddate() {
        return this.dupdateddate;
    }

    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }

    public String getCupdatedby() {
        return this.cupdatedby;
    }

    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }

    public String getCterm() {
        return cterm;
    }

    public void setCterm(String cterm) {
        this.cterm = cterm;
    }

    public Msekolah getMsekolah() {
        return msekolah;
    }

    public void setMsekolah(Msekolah msekolah) {
        this.msekolah = msekolah;
    }

    public Mprodi getMprodi() {
        return mprodi;
    }

    public void setMprodi(Mprodi mprodi) {
        this.mprodi = mprodi;
    }

    public Mtbmtkl getMtbmtkl() {
        return mtbmtkl;
    }

    public void setMtbmtkl(Mtbmtkl mtbmtkl) {
        this.mtbmtkl = mtbmtkl;
    }

    public String getCkelompok() {
        return ckelompok;
    }

    public void setCkelompok(String ckelompok) {
        this.ckelompok = ckelompok;
    }
}


