package id.ac.idu.backend.model;
// Generated 11 Mar 12 23:21:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Tlognilai generated by hbm2java
 */
public class Tlognilai  implements java.io.Serializable {


     private int id;
     private Msekolah msekolah;
     private Mprodi mprodi;
     private Mmahasiswa mmahasiswa;
     private Mtbmtkl mtbmtkl;
     private Mgrade mgrade;
     private String cterm;
     private String ckelompok;
     private String cthajar;
     private String csmt;
     private Integer nsks;
     private String cmun;
     private String cjenis;
     private String cstatus;
     private String ccreatedby;
     private Date dcreateddate;
     private String cupdatedby;
     private Date dupdateddate;

    public Tlognilai() {
    }

	
    public Tlognilai(int id, Msekolah msekolah, Mprodi mprodi, Mmahasiswa mmahasiswa, Mtbmtkl mtbmtkl, String cterm, String ckelompok, String cthajar, String csmt) {
        this.id = id;
        this.msekolah = msekolah;
        this.mprodi = mprodi;
        this.mmahasiswa = mmahasiswa;
        this.mtbmtkl = mtbmtkl;
        this.cterm = cterm;
        this.ckelompok = ckelompok;
        this.cthajar = cthajar;
        this.csmt = csmt;
    }
    public Tlognilai(int id, Msekolah msekolah, Mprodi mprodi, Mmahasiswa mmahasiswa, Mtbmtkl mtbmtkl, Mgrade mgrade, String cterm, String ckelompok, String cthajar, String csmt, Integer nsks, String cmun, String cjenis, String cstatus, String ccreatedby, Date dcreateddate, String cupdatedby, Date dupdateddate) {
       this.id = id;
       this.msekolah = msekolah;
       this.mprodi = mprodi;
       this.mmahasiswa = mmahasiswa;
       this.mtbmtkl = mtbmtkl;
       this.mgrade = mgrade;
       this.cterm = cterm;
       this.ckelompok = ckelompok;
       this.cthajar = cthajar;
       this.csmt = csmt;
       this.nsks = nsks;
       this.cmun = cmun;
       this.cjenis = cjenis;
       this.cstatus = cstatus;
       this.ccreatedby = ccreatedby;
       this.dcreateddate = dcreateddate;
       this.cupdatedby = cupdatedby;
       this.dupdateddate = dupdateddate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Msekolah getMsekolah() {
        return this.msekolah;
    }
    
    public void setMsekolah(Msekolah msekolah) {
        this.msekolah = msekolah;
    }
    public Mprodi getMprodi() {
        return this.mprodi;
    }
    
    public void setMprodi(Mprodi mprodi) {
        this.mprodi = mprodi;
    }
    public Mmahasiswa getMmahasiswa() {
        return this.mmahasiswa;
    }
    
    public void setMmahasiswa(Mmahasiswa mmahasiswa) {
        this.mmahasiswa = mmahasiswa;
    }
    public Mtbmtkl getMtbmtkl() {
        return this.mtbmtkl;
    }
    
    public void setMtbmtkl(Mtbmtkl mtbmtkl) {
        this.mtbmtkl = mtbmtkl;
    }
    public Mgrade getMgrade() {
        return this.mgrade;
    }
    
    public void setMgrade(Mgrade mgrade) {
        this.mgrade = mgrade;
    }
    public String getCterm() {
        return this.cterm;
    }
    
    public void setCterm(String cterm) {
        this.cterm = cterm;
    }
    public String getCkelompok() {
        return this.ckelompok;
    }
    
    public void setCkelompok(String ckelompok) {
        this.ckelompok = ckelompok;
    }
    public String getCthajar() {
        return this.cthajar;
    }
    
    public void setCthajar(String cthajar) {
        this.cthajar = cthajar;
    }
    public String getCsmt() {
        return this.csmt;
    }
    
    public void setCsmt(String csmt) {
        this.csmt = csmt;
    }
    public Integer getNsks() {
        return this.nsks;
    }
    
    public void setNsks(Integer nsks) {
        this.nsks = nsks;
    }
    public String getCmun() {
        return this.cmun;
    }
    
    public void setCmun(String cmun) {
        this.cmun = cmun;
    }
    public String getCjenis() {
        return this.cjenis;
    }
    
    public void setCjenis(String cjenis) {
        this.cjenis = cjenis;
    }
    public String getCstatus() {
        return this.cstatus;
    }
    
    public void setCstatus(String cstatus) {
        this.cstatus = cstatus;
    }
    public String getCcreatedby() {
        return this.ccreatedby;
    }
    
    public void setCcreatedby(String ccreatedby) {
        this.ccreatedby = ccreatedby;
    }
    public Date getDcreateddate() {
        return this.dcreateddate;
    }
    
    public void setDcreateddate(Date dcreateddate) {
        this.dcreateddate = dcreateddate;
    }
    public String getCupdatedby() {
        return this.cupdatedby;
    }
    
    public void setCupdatedby(String cupdatedby) {
        this.cupdatedby = cupdatedby;
    }
    public Date getDupdateddate() {
        return this.dupdateddate;
    }
    
    public void setDupdateddate(Date dupdateddate) {
        this.dupdateddate = dupdateddate;
    }




}


