package id.ac.idu.backend.model;
// Generated 10 Mar 12 12:50:36 by Hibernate Tools 3.2.1.GA


/**
 * TlognilaiId generated by hbm2java
 */
public class TlognilaiId implements java.io.Serializable {


    private String ckdsekolah;
    private String ckdprogst;
    private String cterm;
    private String cthajar;
    private String csmt;
    private String cnim;
    private String ckdmtk;
    private String ckelompok;

    public TlognilaiId() {
    }

    public TlognilaiId(String ckdsekolah, String ckdprogst, String cterm, String cthajar, String csmt, String cnim, String ckdmtk, String ckelompok) {
        this.ckdsekolah = ckdsekolah;
        this.ckdprogst = ckdprogst;
        this.cterm = cterm;
        this.cthajar = cthajar;
        this.csmt = csmt;
        this.cnim = cnim;
        this.ckdmtk = ckdmtk;
        this.ckelompok = ckelompok;
    }

    public String getCkdsekolah() {
        return this.ckdsekolah;
    }

    public void setCkdsekolah(String ckdsekolah) {
        this.ckdsekolah = ckdsekolah;
    }

    public String getCkdprogst() {
        return this.ckdprogst;
    }

    public void setCkdprogst(String ckdprogst) {
        this.ckdprogst = ckdprogst;
    }

    public String getCterm() {
        return this.cterm;
    }

    public void setCterm(String cterm) {
        this.cterm = cterm;
    }

    public String getCthajar() {
        return this.cthajar;
    }

    public void setCthajar(String cthajar) {
        this.cthajar = cthajar;
    }

    public String getCsmt() {
        return this.csmt;
    }

    public void setCsmt(String csmt) {
        this.csmt = csmt;
    }

    public String getCnim() {
        return this.cnim;
    }

    public void setCnim(String cnim) {
        this.cnim = cnim;
    }

    public String getCkdmtk() {
        return this.ckdmtk;
    }

    public void setCkdmtk(String ckdmtk) {
        this.ckdmtk = ckdmtk;
    }

    public String getCkelompok() {
        return this.ckelompok;
    }

    public void setCkelompok(String ckelompok) {
        this.ckelompok = ckelompok;
    }


    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof TlognilaiId)) return false;
        TlognilaiId castOther = (TlognilaiId) other;

        return ((this.getCkdsekolah() == castOther.getCkdsekolah()) || (this.getCkdsekolah() != null && castOther.getCkdsekolah() != null && this.getCkdsekolah().equals(castOther.getCkdsekolah())))
                && ((this.getCkdprogst() == castOther.getCkdprogst()) || (this.getCkdprogst() != null && castOther.getCkdprogst() != null && this.getCkdprogst().equals(castOther.getCkdprogst())))
                && ((this.getCterm() == castOther.getCterm()) || (this.getCterm() != null && castOther.getCterm() != null && this.getCterm().equals(castOther.getCterm())))
                && ((this.getCthajar() == castOther.getCthajar()) || (this.getCthajar() != null && castOther.getCthajar() != null && this.getCthajar().equals(castOther.getCthajar())))
                && ((this.getCsmt() == castOther.getCsmt()) || (this.getCsmt() != null && castOther.getCsmt() != null && this.getCsmt().equals(castOther.getCsmt())))
                && ((this.getCnim() == castOther.getCnim()) || (this.getCnim() != null && castOther.getCnim() != null && this.getCnim().equals(castOther.getCnim())))
                && ((this.getCkdmtk() == castOther.getCkdmtk()) || (this.getCkdmtk() != null && castOther.getCkdmtk() != null && this.getCkdmtk().equals(castOther.getCkdmtk())))
                && ((this.getCkelompok() == castOther.getCkelompok()) || (this.getCkelompok() != null && castOther.getCkelompok() != null && this.getCkelompok().equals(castOther.getCkelompok())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getCkdsekolah() == null ? 0 : this.getCkdsekolah().hashCode());
        result = 37 * result + (getCkdprogst() == null ? 0 : this.getCkdprogst().hashCode());
        result = 37 * result + (getCterm() == null ? 0 : this.getCterm().hashCode());
        result = 37 * result + (getCthajar() == null ? 0 : this.getCthajar().hashCode());
        result = 37 * result + (getCsmt() == null ? 0 : this.getCsmt().hashCode());
        result = 37 * result + (getCnim() == null ? 0 : this.getCnim().hashCode());
        result = 37 * result + (getCkdmtk() == null ? 0 : this.getCkdmtk().hashCode());
        result = 37 * result + (getCkelompok() == null ? 0 : this.getCkelompok().hashCode());
        return result;
    }


}


