DROP TABLE THISTKERJA;

CREATE TABLE THISTKERJA  (
		  ID INTEGER NOT NULL , 
		  CTERM CHAR(4) , 
		  SEKOLAH_ID INTEGER , 
		  PRODI_ID INTEGER , 
		  CNIM CHAR(12) , 
		  ALUMNI_ID INTEGER NOT NULL , 
		  NNOURUT INTEGER NOT NULL , 
		  CJNSINSTANSI CHAR(1) NOT NULL , 
		  CNMINSTANSI VARCHAR(50) NOT NULL , 
		  CALINSTANSI VARCHAR(100) NOT NULL , 
		  BID_USH_INS_ID INTEGER NOT NULL , 
		  CKDKERJA CHAR(2) , 
		  CKDGAJI CHAR(2) , 
		  CCREATEDBY VARCHAR(35) , 
		  CCREATEDDATE DATE , 
		  CUPDATEDBY VARCHAR(35) , 
		  CUPDATEDDATE DATE )   
		 IN USERSPACE1 ; 

CREATE UNIQUE INDEX PK_HISTORY ON THISTKERJA 
		(ID ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

ALTER TABLE THISTKERJA 
	ADD CONSTRAINT PK_HISTORY PRIMARY KEY
		(ID);

ALTER TABLE THISTKERJA 
	ADD CONSTRAINT UN_HISTKERJA UNIQUE
		(ALUMNI_ID,
		 NNOURUT);

ALTER TABLE THISTKERJA 
	ADD CONSTRAINT FK_BIDUSAHA FOREIGN KEY
		(BID_USH_INS_ID)
	REFERENCES MBIDANGUSAHA
		(ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

COMMIT;

CREATE SEQUENCE MBIDANGUSAHA_SEQ INCREMENT BY 1 START WITH 100000;
CREATE SEQUENCE THISTKERJA_SEQ INCREMENT BY 1 START WITH 100000; 
ALTER TABLE THISTKERJA ADD CONSTRAINT UN_HISTKERJA UNIQUE ( ALUMNI_ID, NNOURUT) ;

INSERT INTO MBIDANGUSAHA (ID,CBIDUSHINS,CNMBIDUSAHA) VALUES (1,'TL','TELEKOMUNIKASI');
INSERT INTO MBIDANGUSAHA (ID,CBIDUSHINS,CNMBIDUSAHA) VALUES (2,'TR','TRANSFORTASI');

--ALTER TABLE TFEEDBACKALUMNI ALTER COLUMN CJAWABAN SET NOT NULL;
--ALTER TABLE TFEEDBACKDOSEN ALTER COLUMN CJAWABAN SET NOT NULL;
--ALTER TABLE TFEEDBACKWISUDAWAN ALTER COLUMN CJAWABAN SET NOT NULL;

ALTER TABLE TFEEDBACKALUMNI ALTER COLUMN CTERM SET NOT NULL;
ALTER TABLE TFEEDBACKDOSEN ALTER COLUMN CTERM SET NOT NULL;
ALTER TABLE TFEEDBACKWISUDAWAN ALTER COLUMN CTERM SET NOT NULL;

REORG TABLE TFEEDBACKALUMNI ALLOW READ ACCESS ;
REORG TABLE TFEEDBACKDOSEN ALLOW READ ACCESS ;
REORG TABLE TFEEDBACKWISUDAWAN ALLOW READ ACCESS ;

ALTER TABLE TFEEDBACKALUMNI DROP CONSTRAINT TFEEDBACKALUMNI_UK1;
ALTER TABLE TFEEDBACKDOSEN DROP CONSTRAINT TFEEDBACKDOSEN_UK1;
ALTER TABLE TFEEDBACKWISUDAWAN DROP CONSTRAINT TFEEDBACKWISUDAWAN_UK1;

DELETE FROM TFEEDBACKALUMNI;
DELETE FROM TFEEDBACKDOSEN;
DELETE FROM TFEEDBACKWISUDAWAN;

ALTER TABLE TFEEDBACKALUMNI ADD CONSTRAINT TFEEDBACKALUMNI_UK1
 UNIQUE (MAHASISWA_ID, CTERM, CKELOMPOK, FEEDBACK_ID, NNOPERTANYAAN);
ALTER TABLE TFEEDBACKDOSEN ADD CONSTRAINT TFEEDBACKDOSEN_UK1
 UNIQUE (DOSEN_ID, CTERM, CKELOMPOK, FEEDBACK_ID, NNOPERTANYAAN);
ALTER TABLE TFEEDBACKWISUDAWAN ADD CONSTRAINT TFEEDBACKWISUDAWAN_UK1
 UNIQUE (MAHASISWA_ID, CTERM, CKELOMPOK, FEEDBACK_ID, NNOPERTANYAAN);
COMMIT;