ALTER TABLE TFEEDBACKALUMNI DROP UNIQUE TFEEDBACKALUMNI_UK1 ;
ALTER TABLE TFEEDBACKALUMNI ADD CONSTRAINT TFEEDBACKALUMNI_UK1 UNIQUE (CTERM,SEKOLAH_ID, PRODI_ID, MAHASISWA_ID CKELOMPOK, FEEDBACK_ID, NNOPERTANYAAN);
ALTER TABLE MALUMNI DROP UNIQUE MALUMNI_UK1;
ALTER TABLE MFASILITAS ALTER COLUMN CNAMA_FASILITAS SET DATA TYPE VARCHAR ( 50 ) ;
