--<ScriptOptions statementTerminator=";"/>

ALTER TABLE TFEEDBACKALUMNI DROP CONSTRAINT FK_TFEEDBACKALUMNI_MAHASISWA;

ALTER TABLE TFEEDBACKALUMNI DROP CONSTRAINT FK_TFEEDBACKALUMNI_PRODI;

ALTER TABLE TFEEDBACKALUMNI DROP CONSTRAINT FK_TFEEDBACKALUMNI_FEEDBACK;

ALTER TABLE TFEEDBACKALUMNI DROP CONSTRAINT FK_TFEEDBACKALUMNI_SEKOLAH;

ALTER TABLE TFEEDBACKALUMNI DROP CONSTRAINT PK_TFEEDBACKALUMNI;

DROP INDEX PK_TFEEDBACKALUMNI;

DROP TABLE TFEEDBACKALUMNI;

CREATE TABLE TFEEDBACKALUMNI (
		ID INTEGER NOT NULL,
		CTERM VARCHAR(2) NOT NULL,
		SEKOLAH_ID INTEGER NOT NULL,
		PRODI_ID INTEGER NOT NULL,
		CKELOMPOK VARCHAR(2) NOT NULL,
		MAHASISWA_ID INTEGER NOT NULL,
		FEEDBACK_ID INTEGER NOT NULL,
		NNOPERTANYAAN INTEGER NOT NULL,
		CJAWABAN VARCHAR(1),
		CCREATEDBY VARCHAR(10),
		DCREATEDDATE DATE,
		CUPDATEBY VARCHAR(10),
		DUPDATEDDATE DATE
	);

CREATE UNIQUE INDEX PK_TFEEDBACKALUMNI ON TFEEDBACKALUMNI (ID ASC);

ALTER TABLE TFEEDBACKALUMNI ADD CONSTRAINT PK_TFEEDBACKALUMNI PRIMARY KEY (ID);

ALTER TABLE TFEEDBACKALUMNI ADD CONSTRAINT FK_TFEEDBACKALUMNI_MAHASISWA FOREIGN KEY (MAHASISWA_ID)
	REFERENCES MMAHASISWA (ID);

ALTER TABLE TFEEDBACKALUMNI ADD CONSTRAINT FK_TFEEDBACKALUMNI_PRODI FOREIGN KEY (PRODI_ID)
	REFERENCES MPRODI (ID);

ALTER TABLE TFEEDBACKALUMNI ADD CONSTRAINT FK_TFEEDBACKALUMNI_FEEDBACK FOREIGN KEY (FEEDBACK_ID)
	REFERENCES MFEEDBACK (ID);

ALTER TABLE TFEEDBACKALUMNI ADD CONSTRAINT FK_TFEEDBACKALUMNI_SEKOLAH FOREIGN KEY (SEKOLAH_ID)
	REFERENCES MSEKOLAH (ID);

CREATE SEQUENCE TFEEDBACKALUMNI_SEQ INCREMENT BY 1 START WITH 100000;
